// Per-PROBLEM teaching, keyed by problemId. Fixes the "Learn First is identical
// on every page" problem: the subject teaching model is generic, this is specific
// to the exact task. Codex's Learn First panel should prefer
// problemLessons[activeProblem.id] and fall back to the subject model when absent.
//
// concept = the one idea this problem teaches (plain English).
// idiom   = the key line(s) of code to know.
// mistake = the common pitfall.
//
// Ownership: Claude. Growing batch — Python Fundamentals first (the worst
// offender in the screenshot), more subjects to follow. See PROGRESSION_PLAN.md.

export type ProblemLesson = {
  problemId: string
  concept: string
  idiom: string
  mistake?: string
}

export const problemLessons: ProblemLesson[] = [
  { problemId: 'py-is-even', concept: `Even vs odd is a remainder check: a number is even when dividing by 2 leaves nothing.`, idiom: `return n % 2 == 0`, mistake: `Returning n % 2 gives 0 or 1, not a boolean.` },
  { problemId: 'py-max-of-three', concept: `max() takes several arguments and returns the largest one.`, idiom: `return max(a, b, c)`, mistake: `Hand-writing nested if/else when max() already does it.` },
  { problemId: 'py-sum-loop', concept: `Build a total by adding each item as you loop (an accumulator).`, idiom: `total = 0\nfor n in nums:\n    total += n`, mistake: `Forgetting to initialize total before the loop.` },
  { problemId: 'py-build-range', concept: `range(n) yields 0..n-1; collect the values into a list.`, idiom: `for i in range(n):\n    out.append(i)`, mistake: `range(n) is not a list until you iterate it or wrap it in list().` },
  { problemId: 'py-count-while', concept: `A while loop repeats until its condition becomes false — good for countdowns.`, idiom: `while n > 0:\n    out.append(n)\n    n -= 1`, mistake: `Forgetting to decrement n creates an infinite loop.` },
  { problemId: 'py-evens-up-to', concept: `range(start, stop, step) counts by step.`, idiom: `list(range(0, n, 2))`, mistake: `stop is exclusive — off-by-one is easy here.` },
  { problemId: 'py-factorial', concept: `Factorial multiplies 1 through n with an accumulator.`, idiom: `result = 1\nfor i in range(2, n + 1):\n    result *= i`, mistake: `factorial(0) must be 1, not 0.` },
  { problemId: 'py-fib', concept: `Each Fibonacci number is the sum of the two before it.`, idiom: `a, b = 0, 1\nfor _ in range(n):\n    a, b = b, a + b`, mistake: `Off-by-one on which index you return.` },
  { problemId: 'py-fizzbuzz', concept: `Test divisibility, checking the combined case first.`, idiom: `if i % 15 == 0: 'FizzBuzz'\nelif i % 3 == 0: 'Fizz'`, mistake: `Checking 3 and 5 before 15 misses FizzBuzz.` },
  { problemId: 'py-shout', concept: `str.upper() returns an uppercased copy of the string.`, idiom: `return s.upper()`, mistake: `Strings are immutable; upper() returns a new one.` },
  { problemId: 'py-clean-name', concept: `Chain string methods: strip() trims whitespace, title()/lower() normalize case.`, idiom: `return name.strip().title()`, mistake: `Skipping strip() leaves stray leading/trailing spaces.` },
  { problemId: 'py-has-substring', concept: `The in operator tests substring/membership.`, idiom: `return needle in haystack`, mistake: `Using find() != -1 where in reads cleaner.` },
  { problemId: 'py-is-url', concept: `str.startswith() checks a prefix.`, idiom: `return s.startswith('http')`, mistake: `Slicing s[:4] by hand is brittle.` },
  { problemId: 'py-redact', concept: `str.replace(old, new) swaps every occurrence.`, idiom: `return s.replace(secret, '***')`, mistake: `replace returns a new string; it does not mutate in place.` },
  { problemId: 'py-csv-join', concept: `str.join() glues a list together with a separator.`, idiom: `return ','.join(parts)`, mistake: `join is called on the separator, not on the list.` },
  { problemId: 'py-count-char', concept: `str.count(sub) counts non-overlapping occurrences.`, idiom: `return s.count(ch)`, mistake: `Looping by hand when count() exists.` },
  { problemId: 'py-reverse-string', concept: `Slicing with step -1 reverses a sequence.`, idiom: `return s[::-1]`, mistake: `reversed() returns an iterator, not a string.` },
  { problemId: 'py-reverse-words', concept: `split() into words, reverse the list, join back.`, idiom: `return ' '.join(s.split()[::-1])`, mistake: `Reversing characters instead of word order.` },
  { problemId: 'py-first-n', concept: `Slicing items[:n] takes the first n items.`, idiom: `return items[:n]`, mistake: `Slicing never errors past the end, so no bounds check needed.` },
  { problemId: 'py-position', concept: `list.index raises if missing, so guard with in.`, idiom: `return items.index(x) if x in items else -1`, mistake: `Calling index() on a missing value raises ValueError.` },
  { problemId: 'py-sort-desc', concept: `sorted(reverse=True) returns a new list, high to low.`, idiom: `return sorted(nums, reverse=True)`, mistake: `list.sort() mutates in place and returns None.` },
  { problemId: 'py-sort-by-len', concept: `sorted(key=...) sorts by a computed key.`, idiom: `return sorted(words, key=len)`, mistake: `Passing len() (called) instead of len (the function).` },
  { problemId: 'py-min-max', concept: `min() and max() find the extremes of a sequence.`, idiom: `return [min(nums), max(nums)]`, mistake: `Both raise on an empty list.` },
  { problemId: 'py-with-index', concept: `enumerate yields (index, item) pairs.`, idiom: `for i, x in enumerate(items):`, mistake: `Keeping a manual counter instead of enumerate.` },
  { problemId: 'py-pair-up', concept: `zip pairs up items from multiple iterables.`, idiom: `list(zip(a, b))`, mistake: `zip stops at the shortest input.` },
  { problemId: 'py-word-count', concept: `Tally into a dict, defaulting missing keys to 0.`, idiom: `counts[w] = counts.get(w, 0) + 1`, mistake: `Indexing a missing key directly raises KeyError.` },
  { problemId: 'py-safe-get', concept: `dict.get(key, default) avoids KeyError.`, idiom: `return d.get(key, default)`, mistake: `d[key] raises if absent; get() returns the default.` },
  { problemId: 'py-keys-sorted', concept: `dict.keys() is a view; sort it for ordered keys.`, idiom: `return sorted(d.keys())`, mistake: `Dict order is insertion order, not sorted.` },
  { problemId: 'py-merge-dicts', concept: `{**a, **b} merges two dicts, with b winning conflicts.`, idiom: `return {**a, **b}`, mistake: `Later keys silently overwrite earlier ones.` },
  { problemId: 'py-invert-dict', concept: `A dict comprehension can swap keys and values.`, idiom: `return {v: k for k, v in d.items()}`, mistake: `Duplicate values collapse to a single key.` },
  { problemId: 'py-squares-even', concept: `A list comprehension can filter and map in one line.`, idiom: `[x * x for x in nums if x % 2 == 0]`, mistake: `Putting the if before the for (wrong order).` },
  { problemId: 'py-common-elements', concept: `Set intersection finds items in both collections.`, idiom: `return list(set(a) & set(b))`, mistake: `Sets drop order and duplicates.` },
  { problemId: 'py-all-positive', concept: `all() is True when every item passes; pair it with a generator.`, idiom: `return all(x > 0 for x in nums)`, mistake: `all([]) is True (vacuously).` },
  { problemId: 'py-safe-divide', concept: `try/except handles an error instead of crashing.`, idiom: `try:\n    return a / b\nexcept ZeroDivisionError:\n    return None`, mistake: `A bare except hides real bugs.` },
  { problemId: 'py-memoize', concept: `A decorator wraps a function to cache its results by arguments.`, idiom: `cache = {}\nif args in cache: return cache[args]`, mistake: `A mutable default argument as a cache leaks across calls.` },
  { problemId: 'py-group-by', concept: `Bucket items into a dict of lists by a computed key.`, idiom: `out.setdefault(k, []).append(x)`, mistake: `Overwriting the bucket instead of appending.` },
  { problemId: 'py-match-route', concept: `Compare path segments to a pattern, capturing :params.`, idiom: `pattern.split('/') vs path.split('/')`, mistake: `Not handling a differing number of segments.` },
  { problemId: 'py-string-format', concept: `f-strings interpolate values directly into text.`, idiom: `f"{name} has {count} items"`, mistake: `Forgetting the f prefix leaves literal braces.` },
  { problemId: 'py-zip-dict', concept: `dict(zip(keys, values)) pairs two lists into a dict.`, idiom: `return dict(zip(keys, values))`, mistake: `Mismatched lengths drop the extras.` },
  { problemId: 'py-flatten', concept: `Nest two loops (or extend) to flatten one level.`, idiom: `for sub in nested:\n    out.extend(sub)`, mistake: `append would re-nest; use extend.` },
  { problemId: 'py-filter-lambda', concept: `filter(fn, seq) keeps items where fn is truthy.`, idiom: `list(filter(lambda x: x > 0, nums))`, mistake: `filter returns an iterator; wrap it in list().` },
  { problemId: 'py-dedupe-order', concept: `Track seen items in a set to dedupe while keeping order.`, idiom: `if x not in seen:\n    seen.add(x); out.append(x)`, mistake: `set(items) dedupes but loses order.` },
  { problemId: 'py-sort-dicts', concept: `Sort a list of dicts by a field via a key lambda.`, idiom: `sorted(items, key=lambda d: d[key])`, mistake: `Comparing dicts directly raises a TypeError.` },
  { problemId: 'py-max-by-key', concept: `max(key=...) picks the item with the largest computed value.`, idiom: `return max(items, key=key_fn)`, mistake: `Returning the key value instead of the item.` },
  { problemId: 'py-class-counter', concept: `A class bundles state (self.count) with methods that change it.`, idiom: `def __init__(self):\n    self.count = 0`, mistake: `Forgetting self on attributes and method params.` },
  { problemId: 'py-json-roundtrip', concept: `json.dumps serializes to text; json.loads parses it back.`, idiom: `json.loads(json.dumps(obj))`, mistake: `Mixing up dumps (to string) and loads (from string).` },
  { problemId: 'py-defaultdict-group', concept: `defaultdict(list) auto-creates an empty list per new key.`, idiom: `out[key_fn(x)].append(x)`, mistake: `Return dict(out) if you need plain-dict equality.` },
  { problemId: 'py-is-palindrome', concept: `A palindrome reads the same reversed.`, idiom: `return s == s[::-1]`, mistake: `Not normalizing case/spaces when required.` },
  { problemId: 'py-chunk', concept: `Slice in steps of size to split a list into chunks.`, idiom: `[items[i:i + size] for i in range(0, len(items), size)]`, mistake: `The last chunk may be shorter — that is expected.` },
  { problemId: 'py-running-total', concept: `Emit the accumulator after each addition for cumulative sums.`, idiom: `total += n\nout.append(total)`, mistake: `Appending before adding shifts every value.` },
  { problemId: 'py-rotate', concept: `Slicing splits and recombines to rotate a list.`, idiom: `items[-k:] + items[:-k]`, mistake: `k can exceed length; use k % len(items).` },
  { problemId: 'py-merge-sum', concept: `Merge two dicts, adding values for shared keys.`, idiom: `out[k] = out.get(k, 0) + v`, mistake: `Overwriting instead of summing.` },
  { problemId: 'py-count-words', concept: `collections.Counter tallies occurrences in one call.`, idiom: `dict(Counter(text.split()))`, mistake: `Counter is a dict subclass; convert if you need a plain dict.` },
  { problemId: 'py-two-sum', concept: `A seen-map gives O(n): look for target - n as you go.`, idiom: `if target - n in seen:\n    return [seen[target - n], i]`, mistake: `The double loop is O(n^2).` },
  { problemId: 'py-flatten-deep', concept: `Recursion flattens nesting of any depth.`, idiom: `if isinstance(x, list):\n    out.extend(flatten_deep(x))`, mistake: `Handling only one level of nesting.` },
  { problemId: 'py-fib-memo', concept: `@lru_cache memoizes a function automatically.`, idiom: `@lru_cache(maxsize=None)\ndef fib(n): ...`, mistake: `Plain recursion is exponential without caching.` },
  { problemId: 'py-anagram-groups', concept: `Sorted letters are a canonical key shared by anagrams.`, idiom: `groups[''.join(sorted(w))].append(w)`, mistake: `Comparing words directly misses anagrams.` },

  // ----- JavaScript Fundamentals -----
  { problemId: 'jsf-sum-for', concept: `Accumulate a total with a for...of loop.`, idiom: `let total = 0\nfor (const n of nums) total += n`, mistake: `Forgetting to initialize total before the loop.` },
  { problemId: 'jsf-countdown-while', concept: `A while loop repeats until the condition is false.`, idiom: `while (n > 0) { out.push(n); n-- }`, mistake: `Not decrementing n creates an infinite loop.` },
  { problemId: 'jsf-map-double', concept: `Array.map transforms each element into a new array.`, idiom: `return nums.map((n) => n * 2)`, mistake: `map returns a new array; it does not mutate the original.` },
  { problemId: 'jsf-filter-evens', concept: `Array.filter keeps elements where the test returns true.`, idiom: `return nums.filter((n) => n % 2 === 0)`, mistake: `The callback must return a boolean, not the value.` },
  { problemId: 'jsf-reduce-product', concept: `Array.reduce folds a list down to one value.`, idiom: `return nums.reduce((acc, n) => acc * n, 1)`, mistake: `Use 1 as the initial value for a product, not 0.` },
  { problemId: 'jsf-foreach-total', concept: `forEach runs a side effect per item and returns nothing.`, idiom: `let t = 0\nnums.forEach((n) => { t += n })`, mistake: `Expecting forEach to return a value (it returns undefined).` },
  { problemId: 'jsf-shout', concept: `String.toUpperCase returns an uppercased copy.`, idiom: `return s.toUpperCase()`, mistake: `Strings are immutable; it returns a new string.` },
  { problemId: 'jsf-join-csv', concept: `Array.join glues items together with a separator.`, idiom: `return parts.join(',')`, mistake: `join is called on the array; the separator is the argument.` },
  { problemId: 'jsf-contains', concept: `Array.includes tests membership.`, idiom: `return arr.includes(x)`, mistake: `indexOf !== -1 works but includes reads clearer.` },
  { problemId: 'jsf-position-of', concept: `Array.indexOf returns the index, or -1 if absent.`, idiom: `return arr.indexOf(x)`, mistake: `indexOf uses ===, so no deep/object equality.` },
  { problemId: 'jsf-first-n', concept: `Array.slice(0, n) copies the first n elements.`, idiom: `return arr.slice(0, n)`, mistake: `slice copies; splice mutates the array.` },
  { problemId: 'jsf-key-count', concept: `Object.keys returns an array of an object's keys.`, idiom: `return Object.keys(obj).length`, mistake: `for...in also walks inherited keys.` },
  { problemId: 'jsf-entries', concept: `Object.entries yields [key, value] pairs.`, idiom: `Object.entries(obj)`, mistake: `Order is insertion order for string keys.` },
  { problemId: 'jsf-reverse-str', concept: `Split to an array, reverse, then join to reverse a string.`, idiom: `return s.split('').reverse().join('')`, mistake: `Strings have no .reverse() method.` },
  { problemId: 'jsf-fizzbuzz', concept: `Test divisibility, checking the combined case first.`, idiom: `i % 15 === 0 ? 'FizzBuzz' : i % 3 === 0 ? 'Fizz' : ...`, mistake: `Checking 3 and 5 before 15 misses FizzBuzz.` },

  // ----- API drills (writing real handler code) -----
  { problemId: 'apidrill-route-match', concept: `A router maps a (method, path) pair to a handler.`, idiom: `routes.find((r) => r.method === method && r.path === path)?.handler ?? null`, mistake: `Returning the route object instead of its handler.` },
  { problemId: 'apidrill-parse-params', concept: `Parse query params with sensible defaults.`, idiom: `Number(query.page) || 1`, mistake: `Query values are strings; coerce before using them.` },
  { problemId: 'apidrill-status-for-error', concept: `Map a domain error type to an HTTP status in one place.`, idiom: `({ validation: 400, not_found: 404 })[type] || 500`, mistake: `Scattering status codes across handlers.` },
  { problemId: 'apidrill-paginate', concept: `Return one page plus the totals clients need.`, idiom: `items.slice((page - 1) * perPage, page * perPage)`, mistake: `Off-by-one on the start index.` },
  { problemId: 'apidrill-validate-body', concept: `Validate required/typed fields and collect every error.`, idiom: `if (rule.required && empty) errors[field] = 'required'`, mistake: `Stopping at the first error instead of collecting all.` },
  { problemId: 'apidrill-serialize', concept: `Strip sensitive fields before returning a DTO.`, idiom: `const { password, ...rest } = user\nreturn rest`, mistake: `Leaking internal fields to clients.` },
  { problemId: 'apidrill-authorize', concept: `Gate by identity first, then permission.`, idiom: `if (!user) return 401\nif (user.role !== required) return 403`, mistake: `Confusing 401 (who are you) with 403 (not allowed).` },
  { problemId: 'apidrill-method-guard', concept: `Reject disallowed methods with 405.`, idiom: `allowed.includes(method) ? 200 : 405`, mistake: `Returning 404 for a wrong method.` },
  { problemId: 'apidrill-json-response', concept: `A response is a status, a JSON content-type, and a stringified body.`, idiom: `{ status, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }`, mistake: `Forgetting to JSON.stringify the body.` },
  { problemId: 'apidrill-error-envelope', concept: `Wrap errors in a stable shape with a machine code.`, idiom: `{ error: { code, message, fields? } }`, mistake: `Including a fields key when there are none.` },
  { problemId: 'apidrill-crud-handler', concept: `Dispatch a CRUD request to the right action and status.`, idiom: `GET->200/404, POST->201, DELETE->204, else 405`, mistake: `Returning the wrong status code per verb.` },
  { problemId: 'apidrill-rate-headers', concept: `Expose rate-limit state in X-RateLimit-* headers.`, idiom: `{ 'X-RateLimit-Limit': String(limit) }`, mistake: `Header values must be strings, not numbers.` },
  { problemId: 'apidrill-path-params', concept: `Match a pattern to a path and capture :params.`, idiom: `':id' segment -> params.id = value`, mistake: `Not returning null when the segment counts differ.` },
  { problemId: 'apidrill-rest-router', concept: `A router that matches method + pattern and extracts params.`, idiom: `return { handler, params } // or null`, mistake: `Checking the path before the method.` },
  { problemId: 'apidrill-pagination-links', concept: `Build self / first / last / next / prev page links.`, idiom: `next only when page < totalPages`, mistake: `Emitting next/prev at the first/last page.` },
  { problemId: 'apidrill-merge-patch', concept: `JSON Merge Patch: null deletes, objects merge, else replace.`, idiom: `v === null ? delete : mergeable ? recurse : set`, mistake: `Replacing nested objects instead of merging them.` },
  { problemId: 'apidrill-parse-sort', concept: `Parse "-field,other" into sort directives.`, idiom: `part.startsWith('-') ? desc : asc`, mistake: `Not handling the empty string.` },
  { problemId: 'apidrill-list-envelope', concept: `Wrap a list with pagination meta.`, idiom: `{ data, meta: { page, perPage, total, totalPages } }`, mistake: `Computing totalPages without Math.ceil.` },
  { problemId: 'apidrill-require-fields', concept: `Return which required fields are missing or empty.`, idiom: `fields.filter((f) => body[f] == null || body[f] === '')`, mistake: `Treating 0 or false as missing.` },
  { problemId: 'apidrill-content-type', concept: `Map a file extension to a MIME type with a fallback.`, idiom: `map[ext] || 'application/octet-stream'`, mistake: `No fallback for unknown extensions.` },

  // ----- SQL drills (query semantics in code) -----
  { problemId: 'sqldrill-select-where', concept: `WHERE keeps rows matching a predicate.`, idiom: `rows.filter(predicate)` },
  { problemId: 'sqldrill-project', concept: `SELECT specific columns keeps only chosen fields.`, idiom: `rows.map((r) => pick(r, cols))`, mistake: `Mutating the original rows.` },
  { problemId: 'sqldrill-order-by', concept: `ORDER BY sorts rows; reverse for DESC.`, idiom: `const s = [...rows].sort(...); return desc ? s.reverse() : s`, mistake: `sort() mutates in place; copy first.` },
  { problemId: 'sqldrill-limit-offset', concept: `LIMIT/OFFSET pages with a slice.`, idiom: `rows.slice(offset, offset + n)`, mistake: `offset should default to 0.` },
  { problemId: 'sqldrill-distinct', concept: `DISTINCT keeps the first row per key value.`, idiom: `track seen keys in a Set`, mistake: `Comparing whole rows instead of the key.` },
  { problemId: 'sqldrill-count-by', concept: `COUNT ... GROUP BY tallies rows per key.`, idiom: `out[r[key]] = (out[r[key]] || 0) + 1`, mistake: `undefined + 1 is NaN; default to 0.` },
  { problemId: 'sqldrill-sum', concept: `SUM adds up one column.`, idiom: `rows.reduce((s, r) => s + r[key], 0)` },
  { problemId: 'sqldrill-avg', concept: `AVG is sum over count; guard the empty case.`, idiom: `rows.length ? sum / rows.length : 0`, mistake: `Dividing by zero on an empty list.` },
  { problemId: 'sqldrill-inner-join', concept: `INNER JOIN matches rows on a key and merges them.`, idiom: `index the right side by key, then merge matches`, mistake: `An O(n*m) nested loop instead of a hash index.` },
  { problemId: 'sqldrill-update-where', concept: `UPDATE ... WHERE patches matching rows immutably.`, idiom: `rows.map((r) => (pred(r) ? { ...r, ...patch } : r))`, mistake: `Mutating rows in place.` },

  // ----- TypeScript drills -----
  { problemId: 'ts-typed-sum', concept: `Annotate params and the return so callers are type-checked.`, idiom: `function sum(nums: number[]): number`, mistake: `Omitting the return type lets a wrong return slip through.` },
  { problemId: 'ts-greet', concept: `Type a string parameter and return value.`, idiom: `function greet(name: string): string` },
  { problemId: 'ts-optional-param', concept: `A ? makes a parameter optional, so its type is T | undefined.`, idiom: `function f(x?: number)`, mistake: `Using x without handling undefined.` },
  { problemId: 'ts-interface', concept: `An interface names the shape of an object.`, idiom: `interface User { id: number; name: string }` },
  { problemId: 'ts-discriminated-union', concept: `A shared literal tag lets TS narrow a union by checking it.`, idiom: `{ kind: 'circle'; r: number } | { kind: 'square'; s: number }`, mistake: `Forgetting the discriminant field on a variant.` },
  { problemId: 'ts-generic-identity', concept: `A generic <T> preserves the caller's exact type.`, idiom: `function identity<T>(x: T): T` },
  { problemId: 'ts-generic-first', concept: `Generics plus an optional return type access elements safely.`, idiom: `function first<T>(a: T[]): T | undefined` },
  { problemId: 'ts-keyof-pluck', concept: `keyof with a generic types a property lookup precisely.`, idiom: `function pluck<T, K extends keyof T>(o: T, k: K): T[K]` },
  { problemId: 'ts-record-countby', concept: `Record<K, V> types a dictionary/map object.`, idiom: `Record<string, number>` },
  { problemId: 'ts-partial-defaults', concept: `Partial<T> makes every field optional, ideal for overrides.`, idiom: `function withDefaults(o: Partial<Config>): Config` },
  { problemId: 'ts-map-values', concept: `A generic maps values while preserving the keys.`, idiom: `function mapValues<T, U>(o: Record<string, T>, f: (v: T) => U): Record<string, U>` },
  { problemId: 'ts-as-const-union', concept: `as const freezes literals into a precise union type.`, idiom: `const roles = ['admin', 'user'] as const`, mistake: `Without as const the type widens to string[].` },
  { problemId: 'ts-type-guard', concept: `A type predicate (x is T) narrows the type after a check.`, idiom: `function isString(x: unknown): x is string` },
  { problemId: 'ts-omit', concept: `Omit<T, K> builds a type with some keys removed.`, idiom: `type Public = Omit<User, 'password'>` },
  { problemId: 'ts-pick', concept: `Pick<T, K> keeps only the chosen keys.`, idiom: `type Summary = Pick<User, 'id' | 'name'>` },
  { problemId: 'ts-required', concept: `Required<T> makes all optional fields mandatory.`, idiom: `type FullConfig = Required<Config>` },
  { problemId: 'ts-readonly', concept: `Readonly<T> forbids reassigning fields after creation.`, idiom: `type Frozen = Readonly<User>` },
  { problemId: 'ts-tuple', concept: `A tuple types a fixed-length array by position.`, idiom: `function minmax(n: number[]): [number, number]` },
  { problemId: 'ts-generic-constraint', concept: `extends constrains a generic to a required shape.`, idiom: `function byId<T extends { id: number }>(xs: T[])` },
  { problemId: 'ts-mapped-type', concept: `A mapped type transforms every key of another type.`, idiom: `type Flags<T> = { [K in keyof T]: boolean }` },
  { problemId: 'ts-enum', concept: `An enum names a set of related constants.`, idiom: `enum Status { Active, Inactive }` },
  { problemId: 'ts-union-return', concept: `A union return type models more than one outcome.`, idiom: `function find(): User | null` },
  { problemId: 'ts-stack-class', concept: `A generic class stays type-safe for any element type.`, idiom: `class Stack<T> { private items: T[] = [] }` },
  { problemId: 'ts-result-map', concept: `A discriminated Result<T> models ok/error without throwing.`, idiom: `{ ok: true; value: T } | { ok: false; error: string }` },
  { problemId: 'ts-compact', concept: `A type guard inside filter narrows out null/undefined.`, idiom: `arr.filter((x): x is T => x != null)` },
  { problemId: 'ts-from-entries', concept: `Build a typed Record from [key, value] pairs.`, idiom: `function fromEntries<T>(e: [string, T][]): Record<string, T>` },
  { problemId: 'ts-exhaustive', concept: `Assigning the leftover case to never proves you handled every variant.`, idiom: `const _exhaustive: never = shape`, mistake: `Adding a union case then becomes a compile error (which is the point).` },
  { problemId: 'ts-group-by', concept: `A generic groupBy returns Record<string, T[]>.`, idiom: `(out[key] ||= []).push(item)` },
  { problemId: 'ts-pick-keys', concept: `Generic key-picking returns a precise Pick<T, K>.`, idiom: `function pickKeys<T, K extends keyof T>(o: T, keys: K[]): Pick<T, K>` },
  { problemId: 'ts-merge', concept: `An intersection A & B types a merged object.`, idiom: `function merge<A extends object, B extends object>(a: A, b: B): A & B` },

  // ----- Algorithms & data structures -----
  { problemId: 'algo-binary-search', concept: `Binary search halves a sorted range each step — O(log n).`, idiom: `const mid = (lo + hi) >> 1`, mistake: `It only works on sorted input.` },
  { problemId: 'algo-merge-intervals', concept: `Sort by start, then merge any interval that overlaps the last.`, idiom: `if (cur[0] <= last[1]) last[1] = Math.max(last[1], cur[1])`, mistake: `Forgetting to sort by start first.` },
  { problemId: 'algo-merge-sorted', concept: `Two pointers merge sorted lists in linear time.`, idiom: `a[i] <= b[j] ? push a[i++] : push b[j++]` },
  { problemId: 'algo-two-sum', concept: `A seen-map finds the complement in one pass — O(n).`, idiom: `if (seen.has(target - n)) return [seen.get(target - n), i]`, mistake: `The double loop is O(n^2).` },
  { problemId: 'algo-valid-parens', concept: `A stack matches opening and closing brackets.`, idiom: `push opens; on a close, pop and compare`, mistake: `A close with an empty stack is invalid.` },
  { problemId: 'algo-kth-largest', concept: `Sort descending and index, or use a heap for big inputs.`, idiom: `[...nums].sort((a, b) => b - a)[k - 1]` },
  { problemId: 'algo-gcd', concept: `Euclid's algorithm: gcd(a, b) = gcd(b, a % b).`, idiom: `while (b) [a, b] = [b, a % b]` },
  { problemId: 'ds-trie-autocomplete', concept: `A trie stores strings character by character for fast prefix lookup.`, idiom: `walk the tree one char per node`, mistake: `Scanning all words instead of walking the prefix.` },
  { problemId: 'ds-moving-average', concept: `A sliding window keeps a running sum over the last k items.`, idiom: `sum += incoming - oldest`, mistake: `Recomputing the whole window each step.` },

  // ----- Node Fundamentals -----
  { problemId: 'node-fundamentals-01-sum-with-for-loop', concept: `Accumulate a total with a for...of loop.`, idiom: `let total = 0\nfor (const n of nums) total += n` },
  { problemId: 'node-fundamentals-02-count-even-numbers', concept: `Count items that pass a test.`, idiom: `nums.filter((n) => n % 2 === 0).length` },
  { problemId: 'node-fundamentals-03-while-countdown', concept: `A while loop repeats until its condition is false.`, idiom: `while (n > 0) { out.push(n); n-- }`, mistake: `Forgetting to decrement loops forever.` },
  { problemId: 'node-fundamentals-04-map-user-names', concept: `map pulls one field out of each object.`, idiom: `users.map((u) => u.name)` },
  { problemId: 'node-fundamentals-05-filter-active-users', concept: `filter keeps objects whose flag is true.`, idiom: `users.filter((u) => u.active)` },
  { problemId: 'node-fundamentals-06-find-by-id', concept: `Array.find returns the first match or undefined.`, idiom: `users.find((u) => u.id === id)`, mistake: `find returns undefined when nothing matches.` },
  { problemId: 'node-fundamentals-07-count-by-status', concept: `Tally into an object keyed by a field.`, idiom: `acc[u.status] = (acc[u.status] || 0) + 1` },
  { problemId: 'node-fundamentals-08-safe-json-parse', concept: `Wrap JSON.parse in try/catch to survive bad input.`, idiom: `try { return JSON.parse(s) } catch { return null }`, mistake: `JSON.parse throws on invalid JSON.` },
  { problemId: 'node-fundamentals-09-require-fields', concept: `Return the required fields that are missing.`, idiom: `fields.filter((f) => body[f] == null || body[f] === '')` },
  { problemId: 'node-fundamentals-10-normalize-email', concept: `Trim and lowercase to canonicalize an email.`, idiom: `email.trim().toLowerCase()` },
  { problemId: 'node-fundamentals-11-slug-from-title', concept: `Lowercase and replace non-word runs with hyphens.`, idiom: `title.toLowerCase().replace(/[^a-z0-9]+/g, '-')`, mistake: `Leaving leading/trailing hyphens — trim them.` },
  { problemId: 'node-fundamentals-12-parse-integer-param', concept: `Parse an int with a fallback default.`, idiom: `Number.parseInt(s, 10) || fallback`, mistake: `parseInt of "" is NaN.` },
  { problemId: 'node-fundamentals-13-build-query-string', concept: `URLSearchParams encodes an object into a query string.`, idiom: `new URLSearchParams(obj).toString()` },
  { problemId: 'node-fundamentals-14-read-header-case-insensitive', concept: `HTTP header names are case-insensitive.`, idiom: `headers[name.toLowerCase()]`, mistake: `Looking up the exact case the client sent.` },
  { problemId: 'node-fundamentals-15-basic-auth-parser', concept: `Basic auth is base64(user:pass) after the "Basic " prefix.`, idiom: `atob(header.slice(6)).split(':')` },
  { problemId: 'node-fundamentals-16-error-envelope', concept: `Wrap errors in a stable, coded shape.`, idiom: `{ error: { code, message } }` },
  { problemId: 'node-fundamentals-17-compose-middleware', concept: `Middleware runs in order, each transforming the context.`, idiom: `mws.reduce((ctx, mw) => mw(ctx), ctx)` },
  { problemId: 'node-fundamentals-18-promise-all-settled-summary', concept: `allSettled lets you count fulfilled vs rejected.`, idiom: `results.filter((r) => r.status === 'fulfilled').length` },
  { problemId: 'node-fundamentals-19-timeout-race-shape', concept: `Shape a timeout outcome so callers can branch.`, idiom: `{ ok: false, reason: 'timeout' }` },
  { problemId: 'node-fundamentals-20-retryable-status', concept: `5xx and 429 are retryable; other 4xx are not.`, idiom: `status >= 500 || status === 429`, mistake: `Retrying a 400 just fails again.` },
  { problemId: 'node-fundamentals-21-buffer-byte-length', concept: `Byte length differs from character length for multibyte text.`, idiom: `Buffer.byteLength(s, 'utf8')`, mistake: `s.length counts characters, not bytes.` },
  { problemId: 'node-fundamentals-22-chunk-array-for-batches', concept: `Slice in fixed sizes to batch work.`, idiom: `for (let i = 0; i < a.length; i += size) a.slice(i, i + size)` },
  { problemId: 'node-fundamentals-23-idempotency-key', concept: `Return the stored result when a key repeats.`, idiom: `if (store.has(key)) return store.get(key)`, mistake: `Reprocessing a duplicate causes double effects.` },
  { problemId: 'node-fundamentals-24-redact-secret-fields', concept: `Mask sensitive fields before logging.`, idiom: `{ ...obj, password: '***' }`, mistake: `Logging raw bodies leaks secrets.` },
  { problemId: 'node-fundamentals-25-request-log-line', concept: `A structured log line ties method, path, status, and timing.`, idiom: `\`\${method} \${path} \${status} \${ms}ms\`` },
]
