// Per-PROBLEM teaching, keyed by problemId. Fixes the "Learn First is identical
// on every page" problem: the subject teaching model is generic, this is specific
// to the exact task. Codex's Learn First panel should prefer
// problemLessons[activeProblem.id] and fall back to the subject model when absent.
//
// concept = the one idea this problem teaches (plain English).
// idiom   = the key line(s) of code to know.
// mistake = the common pitfall.
//
// Ownership: Claude. Growing batch — Python Fundamentals first (the worst
// offender in the screenshot), more subjects to follow. See PROGRESSION_PLAN.md.

export type ProblemLesson = {
  problemId: string
  concept: string
  idiom: string
  mistake?: string
  example?: string // a concrete input -> output, shown under the idiom
}

const lessonBase: ProblemLesson[] = [
  { problemId: 'py-is-even', concept: `Even vs odd is a remainder check: a number is even when dividing by 2 leaves nothing.`, idiom: `return n % 2 == 0`, mistake: `Returning n % 2 gives 0 or 1, not a boolean.` },
  { problemId: 'py-max-of-three', concept: `max() takes several arguments and returns the largest one.`, idiom: `return max(a, b, c)`, mistake: `Hand-writing nested if/else when max() already does it.` },
  { problemId: 'py-sum-loop', concept: `Build a total by adding each item as you loop (an accumulator).`, idiom: `total = 0\nfor n in nums:\n    total += n`, mistake: `Forgetting to initialize total before the loop.` },
  { problemId: 'py-build-range', concept: `range(n) yields 0..n-1; collect the values into a list.`, idiom: `for i in range(n):\n    out.append(i)`, mistake: `range(n) is not a list until you iterate it or wrap it in list().` },
  { problemId: 'py-count-while', concept: `A while loop repeats until its condition becomes false — good for countdowns.`, idiom: `while n > 0:\n    out.append(n)\n    n -= 1`, mistake: `Forgetting to decrement n creates an infinite loop.` },
  { problemId: 'py-evens-up-to', concept: `range(start, stop, step) counts by step.`, idiom: `list(range(0, n, 2))`, mistake: `stop is exclusive — off-by-one is easy here.` },
  { problemId: 'py-factorial', concept: `Factorial multiplies 1 through n with an accumulator.`, idiom: `result = 1\nfor i in range(2, n + 1):\n    result *= i`, mistake: `factorial(0) must be 1, not 0.` },
  { problemId: 'py-fib', concept: `Each Fibonacci number is the sum of the two before it.`, idiom: `a, b = 0, 1\nfor _ in range(n):\n    a, b = b, a + b`, mistake: `Off-by-one on which index you return.` },
  { problemId: 'py-fizzbuzz', concept: `Test divisibility, checking the combined case first.`, idiom: `if i % 15 == 0: 'FizzBuzz'\nelif i % 3 == 0: 'Fizz'`, mistake: `Checking 3 and 5 before 15 misses FizzBuzz.` },
  { problemId: 'py-shout', concept: `str.upper() returns an uppercased copy of the string.`, idiom: `return s.upper()`, mistake: `Strings are immutable; upper() returns a new one.` },
  { problemId: 'py-clean-name', concept: `Chain string methods: strip() trims whitespace, title()/lower() normalize case.`, idiom: `return name.strip().title()`, mistake: `Skipping strip() leaves stray leading/trailing spaces.` },
  { problemId: 'py-has-substring', concept: `The in operator tests substring/membership.`, idiom: `return needle in haystack`, mistake: `Using find() != -1 where in reads cleaner.` },
  { problemId: 'py-is-url', concept: `str.startswith() checks a prefix.`, idiom: `return s.startswith('http')`, mistake: `Slicing s[:4] by hand is brittle.` },
  { problemId: 'py-redact', concept: `str.replace(old, new) swaps every occurrence.`, idiom: `return s.replace(secret, '***')`, mistake: `replace returns a new string; it does not mutate in place.` },
  { problemId: 'py-csv-join', concept: `str.join() glues a list together with a separator.`, idiom: `return ','.join(parts)`, mistake: `join is called on the separator, not on the list.` },
  { problemId: 'py-count-char', concept: `str.count(sub) counts non-overlapping occurrences.`, idiom: `return s.count(ch)`, mistake: `Looping by hand when count() exists.` },
  { problemId: 'py-reverse-string', concept: `Slicing with step -1 reverses a sequence.`, idiom: `return s[::-1]`, mistake: `reversed() returns an iterator, not a string.` },
  { problemId: 'py-reverse-words', concept: `split() into words, reverse the list, join back.`, idiom: `return ' '.join(s.split()[::-1])`, mistake: `Reversing characters instead of word order.` },
  { problemId: 'py-first-n', concept: `Slicing items[:n] takes the first n items.`, idiom: `return items[:n]`, mistake: `Slicing never errors past the end, so no bounds check needed.` },
  { problemId: 'py-position', concept: `list.index raises if missing, so guard with in.`, idiom: `return items.index(x) if x in items else -1`, mistake: `Calling index() on a missing value raises ValueError.` },
  { problemId: 'py-sort-desc', concept: `sorted(reverse=True) returns a new list, high to low.`, idiom: `return sorted(nums, reverse=True)`, mistake: `list.sort() mutates in place and returns None.` },
  { problemId: 'py-sort-by-len', concept: `sorted(key=...) sorts by a computed key.`, idiom: `return sorted(words, key=len)`, mistake: `Passing len() (called) instead of len (the function).` },
  { problemId: 'py-min-max', concept: `min() and max() find the extremes of a sequence.`, idiom: `return [min(nums), max(nums)]`, mistake: `Both raise on an empty list.` },
  { problemId: 'py-with-index', concept: `enumerate yields (index, item) pairs.`, idiom: `for i, x in enumerate(items):`, mistake: `Keeping a manual counter instead of enumerate.` },
  { problemId: 'py-pair-up', concept: `zip pairs up items from multiple iterables.`, idiom: `list(zip(a, b))`, mistake: `zip stops at the shortest input.` },
  { problemId: 'py-word-count', concept: `Tally into a dict, defaulting missing keys to 0.`, idiom: `counts[w] = counts.get(w, 0) + 1`, mistake: `Indexing a missing key directly raises KeyError.` },
  { problemId: 'py-safe-get', concept: `dict.get(key, default) avoids KeyError.`, idiom: `return d.get(key, default)`, mistake: `d[key] raises if absent; get() returns the default.` },
  { problemId: 'py-keys-sorted', concept: `dict.keys() is a view; sort it for ordered keys.`, idiom: `return sorted(d.keys())`, mistake: `Dict order is insertion order, not sorted.` },
  { problemId: 'py-merge-dicts', concept: `{**a, **b} merges two dicts, with b winning conflicts.`, idiom: `return {**a, **b}`, mistake: `Later keys silently overwrite earlier ones.` },
  { problemId: 'py-invert-dict', concept: `A dict comprehension can swap keys and values.`, idiom: `return {v: k for k, v in d.items()}`, mistake: `Duplicate values collapse to a single key.` },
  { problemId: 'py-squares-even', concept: `A list comprehension can filter and map in one line.`, idiom: `[x * x for x in nums if x % 2 == 0]`, mistake: `Putting the if before the for (wrong order).` },
  { problemId: 'py-common-elements', concept: `Set intersection finds items in both collections.`, idiom: `return list(set(a) & set(b))`, mistake: `Sets drop order and duplicates.` },
  { problemId: 'py-all-positive', concept: `all() is True when every item passes; pair it with a generator.`, idiom: `return all(x > 0 for x in nums)`, mistake: `all([]) is True (vacuously).` },
  { problemId: 'py-safe-divide', concept: `try/except handles an error instead of crashing.`, idiom: `try:\n    return a / b\nexcept ZeroDivisionError:\n    return None`, mistake: `A bare except hides real bugs.` },
  { problemId: 'py-memoize', concept: `A decorator wraps a function to cache its results by arguments.`, idiom: `cache = {}\nif args in cache: return cache[args]`, mistake: `A mutable default argument as a cache leaks across calls.` },
  { problemId: 'py-group-by', concept: `Bucket items into a dict of lists by a computed key.`, idiom: `out.setdefault(k, []).append(x)`, mistake: `Overwriting the bucket instead of appending.` },
  { problemId: 'py-match-route', concept: `Compare path segments to a pattern, capturing :params.`, idiom: `pattern.split('/') vs path.split('/')`, mistake: `Not handling a differing number of segments.` },
  { problemId: 'py-string-format', concept: `f-strings interpolate values directly into text.`, idiom: `f"{name} has {count} items"`, mistake: `Forgetting the f prefix leaves literal braces.` },
  { problemId: 'py-zip-dict', concept: `dict(zip(keys, values)) pairs two lists into a dict.`, idiom: `return dict(zip(keys, values))`, mistake: `Mismatched lengths drop the extras.` },
  { problemId: 'py-flatten', concept: `Nest two loops (or extend) to flatten one level.`, idiom: `for sub in nested:\n    out.extend(sub)`, mistake: `append would re-nest; use extend.` },
  { problemId: 'py-filter-lambda', concept: `filter(fn, seq) keeps items where fn is truthy.`, idiom: `list(filter(lambda x: x > 0, nums))`, mistake: `filter returns an iterator; wrap it in list().` },
  { problemId: 'py-dedupe-order', concept: `Track seen items in a set to dedupe while keeping order.`, idiom: `if x not in seen:\n    seen.add(x); out.append(x)`, mistake: `set(items) dedupes but loses order.` },
  { problemId: 'py-sort-dicts', concept: `Sort a list of dicts by a field via a key lambda.`, idiom: `sorted(items, key=lambda d: d[key])`, mistake: `Comparing dicts directly raises a TypeError.` },
  { problemId: 'py-max-by-key', concept: `max(key=...) picks the item with the largest computed value.`, idiom: `return max(items, key=key_fn)`, mistake: `Returning the key value instead of the item.` },
  { problemId: 'py-class-counter', concept: `A class bundles state (self.count) with methods that change it.`, idiom: `def __init__(self):\n    self.count = 0`, mistake: `Forgetting self on attributes and method params.` },
  { problemId: 'py-json-roundtrip', concept: `json.dumps serializes to text; json.loads parses it back.`, idiom: `json.loads(json.dumps(obj))`, mistake: `Mixing up dumps (to string) and loads (from string).` },
  { problemId: 'py-defaultdict-group', concept: `defaultdict(list) auto-creates an empty list per new key.`, idiom: `out[key_fn(x)].append(x)`, mistake: `Return dict(out) if you need plain-dict equality.` },
  { problemId: 'py-is-palindrome', concept: `A palindrome reads the same reversed.`, idiom: `return s == s[::-1]`, mistake: `Not normalizing case/spaces when required.` },
  { problemId: 'py-chunk', concept: `Slice in steps of size to split a list into chunks.`, idiom: `[items[i:i + size] for i in range(0, len(items), size)]`, mistake: `The last chunk may be shorter — that is expected.` },
  { problemId: 'py-running-total', concept: `Emit the accumulator after each addition for cumulative sums.`, idiom: `total += n\nout.append(total)`, mistake: `Appending before adding shifts every value.` },
  { problemId: 'py-rotate', concept: `Slicing splits and recombines to rotate a list.`, idiom: `items[-k:] + items[:-k]`, mistake: `k can exceed length; use k % len(items).` },
  { problemId: 'py-merge-sum', concept: `Merge two dicts, adding values for shared keys.`, idiom: `out[k] = out.get(k, 0) + v`, mistake: `Overwriting instead of summing.` },
  { problemId: 'py-count-words', concept: `collections.Counter tallies occurrences in one call.`, idiom: `dict(Counter(text.split()))`, mistake: `Counter is a dict subclass; convert if you need a plain dict.` },
  { problemId: 'py-two-sum', concept: `A seen-map gives O(n): look for target - n as you go.`, idiom: `if target - n in seen:\n    return [seen[target - n], i]`, mistake: `The double loop is O(n^2).` },
  { problemId: 'py-flatten-deep', concept: `Recursion flattens nesting of any depth.`, idiom: `if isinstance(x, list):\n    out.extend(flatten_deep(x))`, mistake: `Handling only one level of nesting.` },
  { problemId: 'py-fib-memo', concept: `@lru_cache memoizes a function automatically.`, idiom: `@lru_cache(maxsize=None)\ndef fib(n): ...`, mistake: `Plain recursion is exponential without caching.` },
  { problemId: 'py-anagram-groups', concept: `Sorted letters are a canonical key shared by anagrams.`, idiom: `groups[''.join(sorted(w))].append(w)`, mistake: `Comparing words directly misses anagrams.` },

  // ----- JavaScript Fundamentals -----
  { problemId: 'jsf-sum-for', concept: `Accumulate a total with a for...of loop.`, idiom: `let total = 0\nfor (const n of nums) total += n`, mistake: `Forgetting to initialize total before the loop.` },
  { problemId: 'jsf-countdown-while', concept: `A while loop repeats until the condition is false.`, idiom: `while (n > 0) { out.push(n); n-- }`, mistake: `Not decrementing n creates an infinite loop.` },
  { problemId: 'jsf-map-double', concept: `Array.map transforms each element into a new array.`, idiom: `return nums.map((n) => n * 2)`, mistake: `map returns a new array; it does not mutate the original.` },
  { problemId: 'jsf-filter-evens', concept: `Array.filter keeps elements where the test returns true.`, idiom: `return nums.filter((n) => n % 2 === 0)`, mistake: `The callback must return a boolean, not the value.` },
  { problemId: 'jsf-reduce-product', concept: `Array.reduce folds a list down to one value.`, idiom: `return nums.reduce((acc, n) => acc * n, 1)`, mistake: `Use 1 as the initial value for a product, not 0.` },
  { problemId: 'jsf-foreach-total', concept: `forEach runs a side effect per item and returns nothing.`, idiom: `let t = 0\nnums.forEach((n) => { t += n })`, mistake: `Expecting forEach to return a value (it returns undefined).` },
  { problemId: 'jsf-shout', concept: `String.toUpperCase returns an uppercased copy.`, idiom: `return s.toUpperCase()`, mistake: `Strings are immutable; it returns a new string.` },
  { problemId: 'jsf-join-csv', concept: `Array.join glues items together with a separator.`, idiom: `return parts.join(',')`, mistake: `join is called on the array; the separator is the argument.` },
  { problemId: 'jsf-contains', concept: `Array.includes tests membership.`, idiom: `return arr.includes(x)`, mistake: `indexOf !== -1 works but includes reads clearer.` },
  { problemId: 'jsf-position-of', concept: `Array.indexOf returns the index, or -1 if absent.`, idiom: `return arr.indexOf(x)`, mistake: `indexOf uses ===, so no deep/object equality.` },
  { problemId: 'jsf-first-n', concept: `Array.slice(0, n) copies the first n elements.`, idiom: `return arr.slice(0, n)`, mistake: `slice copies; splice mutates the array.` },
  { problemId: 'jsf-key-count', concept: `Object.keys returns an array of an object's keys.`, idiom: `return Object.keys(obj).length`, mistake: `for...in also walks inherited keys.` },
  { problemId: 'jsf-entries', concept: `Object.entries yields [key, value] pairs.`, idiom: `Object.entries(obj)`, mistake: `Order is insertion order for string keys.` },
  { problemId: 'jsf-reverse-str', concept: `Split to an array, reverse, then join to reverse a string.`, idiom: `return s.split('').reverse().join('')`, mistake: `Strings have no .reverse() method.` },
  { problemId: 'jsf-fizzbuzz', concept: `Test divisibility, checking the combined case first.`, idiom: `i % 15 === 0 ? 'FizzBuzz' : i % 3 === 0 ? 'Fizz' : ...`, mistake: `Checking 3 and 5 before 15 misses FizzBuzz.` },

  // ----- API drills (writing real handler code) -----
  { problemId: 'apidrill-route-match', concept: `A router maps a (method, path) pair to a handler.`, idiom: `routes.find((r) => r.method === method && r.path === path)?.handler ?? null`, mistake: `Returning the route object instead of its handler.` },
  { problemId: 'apidrill-parse-params', concept: `Parse query params with sensible defaults.`, idiom: `Number(query.page) || 1`, mistake: `Query values are strings; coerce before using them.` },
  { problemId: 'apidrill-status-for-error', concept: `Map a domain error type to an HTTP status in one place.`, idiom: `({ validation: 400, not_found: 404 })[type] || 500`, mistake: `Scattering status codes across handlers.` },
  { problemId: 'apidrill-paginate', concept: `Return one page plus the totals clients need.`, idiom: `items.slice((page - 1) * perPage, page * perPage)`, mistake: `Off-by-one on the start index.` },
  { problemId: 'apidrill-validate-body', concept: `Validate required/typed fields and collect every error.`, idiom: `if (rule.required && empty) errors[field] = 'required'`, mistake: `Stopping at the first error instead of collecting all.` },
  { problemId: 'apidrill-serialize', concept: `Strip sensitive fields before returning a DTO.`, idiom: `const { password, ...rest } = user\nreturn rest`, mistake: `Leaking internal fields to clients.` },
  { problemId: 'apidrill-authorize', concept: `Gate by identity first, then permission.`, idiom: `if (!user) return 401\nif (user.role !== required) return 403`, mistake: `Confusing 401 (who are you) with 403 (not allowed).` },
  { problemId: 'apidrill-method-guard', concept: `Reject disallowed methods with 405.`, idiom: `allowed.includes(method) ? 200 : 405`, mistake: `Returning 404 for a wrong method.` },
  { problemId: 'apidrill-json-response', concept: `A response is a status, a JSON content-type, and a stringified body.`, idiom: `{ status, headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }`, mistake: `Forgetting to JSON.stringify the body.` },
  { problemId: 'apidrill-error-envelope', concept: `Wrap errors in a stable shape with a machine code.`, idiom: `{ error: { code, message, fields? } }`, mistake: `Including a fields key when there are none.` },
  { problemId: 'apidrill-crud-handler', concept: `Dispatch a CRUD request to the right action and status.`, idiom: `GET->200/404, POST->201, DELETE->204, else 405`, mistake: `Returning the wrong status code per verb.` },
  { problemId: 'apidrill-rate-headers', concept: `Expose rate-limit state in X-RateLimit-* headers.`, idiom: `{ 'X-RateLimit-Limit': String(limit) }`, mistake: `Header values must be strings, not numbers.` },
  { problemId: 'apidrill-path-params', concept: `Match a pattern to a path and capture :params.`, idiom: `':id' segment -> params.id = value`, mistake: `Not returning null when the segment counts differ.` },
  { problemId: 'apidrill-rest-router', concept: `A router that matches method + pattern and extracts params.`, idiom: `return { handler, params } // or null`, mistake: `Checking the path before the method.` },
  { problemId: 'apidrill-pagination-links', concept: `Build self / first / last / next / prev page links.`, idiom: `next only when page < totalPages`, mistake: `Emitting next/prev at the first/last page.` },
  { problemId: 'apidrill-merge-patch', concept: `JSON Merge Patch: null deletes, objects merge, else replace.`, idiom: `v === null ? delete : mergeable ? recurse : set`, mistake: `Replacing nested objects instead of merging them.` },
  { problemId: 'apidrill-parse-sort', concept: `Parse "-field,other" into sort directives.`, idiom: `part.startsWith('-') ? desc : asc`, mistake: `Not handling the empty string.` },
  { problemId: 'apidrill-list-envelope', concept: `Wrap a list with pagination meta.`, idiom: `{ data, meta: { page, perPage, total, totalPages } }`, mistake: `Computing totalPages without Math.ceil.` },
  { problemId: 'apidrill-require-fields', concept: `Return which required fields are missing or empty.`, idiom: `fields.filter((f) => body[f] == null || body[f] === '')`, mistake: `Treating 0 or false as missing.` },
  { problemId: 'apidrill-content-type', concept: `Map a file extension to a MIME type with a fallback.`, idiom: `map[ext] || 'application/octet-stream'`, mistake: `No fallback for unknown extensions.` },

  // ----- SQL drills (query semantics in code) -----
  { problemId: 'sqldrill-select-where', concept: `WHERE keeps rows matching a predicate.`, idiom: `rows.filter(predicate)` },
  { problemId: 'sqldrill-project', concept: `SELECT specific columns keeps only chosen fields.`, idiom: `rows.map((r) => pick(r, cols))`, mistake: `Mutating the original rows.` },
  { problemId: 'sqldrill-order-by', concept: `ORDER BY sorts rows; reverse for DESC.`, idiom: `const s = [...rows].sort(...); return desc ? s.reverse() : s`, mistake: `sort() mutates in place; copy first.` },
  { problemId: 'sqldrill-limit-offset', concept: `LIMIT/OFFSET pages with a slice.`, idiom: `rows.slice(offset, offset + n)`, mistake: `offset should default to 0.` },
  { problemId: 'sqldrill-distinct', concept: `DISTINCT keeps the first row per key value.`, idiom: `track seen keys in a Set`, mistake: `Comparing whole rows instead of the key.` },
  { problemId: 'sqldrill-count-by', concept: `COUNT ... GROUP BY tallies rows per key.`, idiom: `out[r[key]] = (out[r[key]] || 0) + 1`, mistake: `undefined + 1 is NaN; default to 0.` },
  { problemId: 'sqldrill-sum', concept: `SUM adds up one column.`, idiom: `rows.reduce((s, r) => s + r[key], 0)` },
  { problemId: 'sqldrill-avg', concept: `AVG is sum over count; guard the empty case.`, idiom: `rows.length ? sum / rows.length : 0`, mistake: `Dividing by zero on an empty list.` },
  { problemId: 'sqldrill-inner-join', concept: `INNER JOIN matches rows on a key and merges them.`, idiom: `index the right side by key, then merge matches`, mistake: `An O(n*m) nested loop instead of a hash index.` },
  { problemId: 'sqldrill-update-where', concept: `UPDATE ... WHERE patches matching rows immutably.`, idiom: `rows.map((r) => (pred(r) ? { ...r, ...patch } : r))`, mistake: `Mutating rows in place.` },

  // ----- TypeScript drills -----
  { problemId: 'ts-typed-sum', concept: `Annotate params and the return so callers are type-checked.`, idiom: `function sum(nums: number[]): number`, mistake: `Omitting the return type lets a wrong return slip through.` },
  { problemId: 'ts-greet', concept: `Type a string parameter and return value.`, idiom: `function greet(name: string): string` },
  { problemId: 'ts-optional-param', concept: `A ? makes a parameter optional, so its type is T | undefined.`, idiom: `function f(x?: number)`, mistake: `Using x without handling undefined.` },
  { problemId: 'ts-interface', concept: `An interface names the shape of an object.`, idiom: `interface User { id: number; name: string }` },
  { problemId: 'ts-discriminated-union', concept: `A shared literal tag lets TS narrow a union by checking it.`, idiom: `{ kind: 'circle'; r: number } | { kind: 'square'; s: number }`, mistake: `Forgetting the discriminant field on a variant.` },
  { problemId: 'ts-generic-identity', concept: `A generic <T> preserves the caller's exact type.`, idiom: `function identity<T>(x: T): T` },
  { problemId: 'ts-generic-first', concept: `Generics plus an optional return type access elements safely.`, idiom: `function first<T>(a: T[]): T | undefined` },
  { problemId: 'ts-keyof-pluck', concept: `keyof with a generic types a property lookup precisely.`, idiom: `function pluck<T, K extends keyof T>(o: T, k: K): T[K]` },
  { problemId: 'ts-record-countby', concept: `Record<K, V> types a dictionary/map object.`, idiom: `Record<string, number>` },
  { problemId: 'ts-partial-defaults', concept: `Partial<T> makes every field optional, ideal for overrides.`, idiom: `function withDefaults(o: Partial<Config>): Config` },
  { problemId: 'ts-map-values', concept: `A generic maps values while preserving the keys.`, idiom: `function mapValues<T, U>(o: Record<string, T>, f: (v: T) => U): Record<string, U>` },
  { problemId: 'ts-as-const-union', concept: `as const freezes literals into a precise union type.`, idiom: `const roles = ['admin', 'user'] as const`, mistake: `Without as const the type widens to string[].` },
  { problemId: 'ts-type-guard', concept: `A type predicate (x is T) narrows the type after a check.`, idiom: `function isString(x: unknown): x is string` },
  { problemId: 'ts-omit', concept: `Omit<T, K> builds a type with some keys removed.`, idiom: `type Public = Omit<User, 'password'>` },
  { problemId: 'ts-pick', concept: `Pick<T, K> keeps only the chosen keys.`, idiom: `type Summary = Pick<User, 'id' | 'name'>` },
  { problemId: 'ts-required', concept: `Required<T> makes all optional fields mandatory.`, idiom: `type FullConfig = Required<Config>` },
  { problemId: 'ts-readonly', concept: `Readonly<T> forbids reassigning fields after creation.`, idiom: `type Frozen = Readonly<User>` },
  { problemId: 'ts-tuple', concept: `A tuple types a fixed-length array by position.`, idiom: `function minmax(n: number[]): [number, number]` },
  { problemId: 'ts-generic-constraint', concept: `extends constrains a generic to a required shape.`, idiom: `function byId<T extends { id: number }>(xs: T[])` },
  { problemId: 'ts-mapped-type', concept: `A mapped type transforms every key of another type.`, idiom: `type Flags<T> = { [K in keyof T]: boolean }` },
  { problemId: 'ts-enum', concept: `An enum names a set of related constants.`, idiom: `enum Status { Active, Inactive }` },
  { problemId: 'ts-union-return', concept: `A union return type models more than one outcome.`, idiom: `function find(): User | null` },
  { problemId: 'ts-stack-class', concept: `A generic class stays type-safe for any element type.`, idiom: `class Stack<T> { private items: T[] = [] }` },
  { problemId: 'ts-result-map', concept: `A discriminated Result<T> models ok/error without throwing.`, idiom: `{ ok: true; value: T } | { ok: false; error: string }` },
  { problemId: 'ts-compact', concept: `A type guard inside filter narrows out null/undefined.`, idiom: `arr.filter((x): x is T => x != null)` },
  { problemId: 'ts-from-entries', concept: `Build a typed Record from [key, value] pairs.`, idiom: `function fromEntries<T>(e: [string, T][]): Record<string, T>` },
  { problemId: 'ts-exhaustive', concept: `Assigning the leftover case to never proves you handled every variant.`, idiom: `const _exhaustive: never = shape`, mistake: `Adding a union case then becomes a compile error (which is the point).` },
  { problemId: 'ts-group-by', concept: `A generic groupBy returns Record<string, T[]>.`, idiom: `(out[key] ||= []).push(item)` },
  { problemId: 'ts-pick-keys', concept: `Generic key-picking returns a precise Pick<T, K>.`, idiom: `function pickKeys<T, K extends keyof T>(o: T, keys: K[]): Pick<T, K>` },
  { problemId: 'ts-merge', concept: `An intersection A & B types a merged object.`, idiom: `function merge<A extends object, B extends object>(a: A, b: B): A & B` },

  // ----- Algorithms & data structures -----
  { problemId: 'algo-binary-search', concept: `Binary search halves a sorted range each step — O(log n).`, idiom: `const mid = (lo + hi) >> 1`, mistake: `It only works on sorted input.` },
  { problemId: 'algo-merge-intervals', concept: `Sort by start, then merge any interval that overlaps the last.`, idiom: `if (cur[0] <= last[1]) last[1] = Math.max(last[1], cur[1])`, mistake: `Forgetting to sort by start first.` },
  { problemId: 'algo-merge-sorted', concept: `Two pointers merge sorted lists in linear time.`, idiom: `a[i] <= b[j] ? push a[i++] : push b[j++]` },
  { problemId: 'algo-two-sum', concept: `A seen-map finds the complement in one pass — O(n).`, idiom: `if (seen.has(target - n)) return [seen.get(target - n), i]`, mistake: `The double loop is O(n^2).` },
  { problemId: 'algo-valid-parens', concept: `A stack matches opening and closing brackets.`, idiom: `push opens; on a close, pop and compare`, mistake: `A close with an empty stack is invalid.` },
  { problemId: 'algo-kth-largest', concept: `Sort descending and index, or use a heap for big inputs.`, idiom: `[...nums].sort((a, b) => b - a)[k - 1]` },
  { problemId: 'algo-gcd', concept: `Euclid's algorithm: gcd(a, b) = gcd(b, a % b).`, idiom: `while (b) [a, b] = [b, a % b]` },
  { problemId: 'ds-trie-autocomplete', concept: `A trie stores strings character by character for fast prefix lookup.`, idiom: `walk the tree one char per node`, mistake: `Scanning all words instead of walking the prefix.` },
  { problemId: 'ds-moving-average', concept: `A sliding window keeps a running sum over the last k items.`, idiom: `sum += incoming - oldest`, mistake: `Recomputing the whole window each step.` },

  // ----- Node Fundamentals -----
  { problemId: 'node-fundamentals-01-sum-with-for-loop', concept: `Accumulate a total with a for...of loop.`, idiom: `let total = 0\nfor (const n of nums) total += n` },
  { problemId: 'node-fundamentals-02-count-even-numbers', concept: `Count items that pass a test.`, idiom: `nums.filter((n) => n % 2 === 0).length` },
  { problemId: 'node-fundamentals-03-while-countdown', concept: `A while loop repeats until its condition is false.`, idiom: `while (n > 0) { out.push(n); n-- }`, mistake: `Forgetting to decrement loops forever.` },
  { problemId: 'node-fundamentals-04-map-user-names', concept: `map pulls one field out of each object.`, idiom: `users.map((u) => u.name)` },
  { problemId: 'node-fundamentals-05-filter-active-users', concept: `filter keeps objects whose flag is true.`, idiom: `users.filter((u) => u.active)` },
  { problemId: 'node-fundamentals-06-find-by-id', concept: `Array.find returns the first match or undefined.`, idiom: `users.find((u) => u.id === id)`, mistake: `find returns undefined when nothing matches.` },
  { problemId: 'node-fundamentals-07-count-by-status', concept: `Tally into an object keyed by a field.`, idiom: `acc[u.status] = (acc[u.status] || 0) + 1` },
  { problemId: 'node-fundamentals-08-safe-json-parse', concept: `Wrap JSON.parse in try/catch to survive bad input.`, idiom: `try { return JSON.parse(s) } catch { return null }`, mistake: `JSON.parse throws on invalid JSON.` },
  { problemId: 'node-fundamentals-09-require-fields', concept: `Return the required fields that are missing.`, idiom: `fields.filter((f) => body[f] == null || body[f] === '')` },
  { problemId: 'node-fundamentals-10-normalize-email', concept: `Trim and lowercase to canonicalize an email.`, idiom: `email.trim().toLowerCase()` },
  { problemId: 'node-fundamentals-11-slug-from-title', concept: `Lowercase and replace non-word runs with hyphens.`, idiom: `title.toLowerCase().replace(/[^a-z0-9]+/g, '-')`, mistake: `Leaving leading/trailing hyphens — trim them.` },
  { problemId: 'node-fundamentals-12-parse-integer-param', concept: `Parse an int with a fallback default.`, idiom: `Number.parseInt(s, 10) || fallback`, mistake: `parseInt of "" is NaN.` },
  { problemId: 'node-fundamentals-13-build-query-string', concept: `URLSearchParams encodes an object into a query string.`, idiom: `new URLSearchParams(obj).toString()` },
  { problemId: 'node-fundamentals-14-read-header-case-insensitive', concept: `HTTP header names are case-insensitive.`, idiom: `headers[name.toLowerCase()]`, mistake: `Looking up the exact case the client sent.` },
  { problemId: 'node-fundamentals-15-basic-auth-parser', concept: `Basic auth is base64(user:pass) after the "Basic " prefix.`, idiom: `atob(header.slice(6)).split(':')` },
  { problemId: 'node-fundamentals-16-error-envelope', concept: `Wrap errors in a stable, coded shape.`, idiom: `{ error: { code, message } }` },
  { problemId: 'node-fundamentals-17-compose-middleware', concept: `Middleware runs in order, each transforming the context.`, idiom: `mws.reduce((ctx, mw) => mw(ctx), ctx)` },
  { problemId: 'node-fundamentals-18-promise-all-settled-summary', concept: `allSettled lets you count fulfilled vs rejected.`, idiom: `results.filter((r) => r.status === 'fulfilled').length` },
  { problemId: 'node-fundamentals-19-timeout-race-shape', concept: `Shape a timeout outcome so callers can branch.`, idiom: `{ ok: false, reason: 'timeout' }` },
  { problemId: 'node-fundamentals-20-retryable-status', concept: `5xx and 429 are retryable; other 4xx are not.`, idiom: `status >= 500 || status === 429`, mistake: `Retrying a 400 just fails again.` },
  { problemId: 'node-fundamentals-21-buffer-byte-length', concept: `Byte length differs from character length for multibyte text.`, idiom: `Buffer.byteLength(s, 'utf8')`, mistake: `s.length counts characters, not bytes.` },
  { problemId: 'node-fundamentals-22-chunk-array-for-batches', concept: `Slice in fixed sizes to batch work.`, idiom: `for (let i = 0; i < a.length; i += size) a.slice(i, i + size)` },
  { problemId: 'node-fundamentals-23-idempotency-key', concept: `Return the stored result when a key repeats.`, idiom: `if (store.has(key)) return store.get(key)`, mistake: `Reprocessing a duplicate causes double effects.` },
  { problemId: 'node-fundamentals-24-redact-secret-fields', concept: `Mask sensitive fields before logging.`, idiom: `{ ...obj, password: '***' }`, mistake: `Logging raw bodies leaks secrets.` },
  { problemId: 'node-fundamentals-25-request-log-line', concept: `A structured log line ties method, path, status, and timing.`, idiom: `\`\${method} \${path} \${status} \${ms}ms\`` },

  // ----- Internet & HTTP -----
  { problemId: 'internet-request-line', concept: `An HTTP request line is three tokens: method, target, version.`, idiom: `const [method, target, version] = line.split(' ')` },
  { problemId: 'internet-parse-cookies', concept: `A Cookie header is "k=v; k2=v2" pairs.`, idiom: `header.split('; ').map((p) => p.split('='))` },
  { problemId: 'internet-build-response', concept: `A raw response is a status line, headers, a blank line, then the body.`, idiom: `status line + CRLF headers + blank line + body`, mistake: `Content-Length must be the byte length.` },
  { problemId: 'internet-content-negotiation', concept: `Accept lists media types with q-weights; pick the best you can serve.`, idiom: `sort by q desc, take first servable` },
  { problemId: 'internet-query-parser', concept: `Parse "?a=1&b=2" into an object.`, idiom: `split('&').map((p) => p.split('='))` },
  { problemId: 'http-build-query', concept: `Encode an object into a query string.`, idiom: `new URLSearchParams(obj).toString()` },
  { problemId: 'http-parse-cache-control', concept: `Parse Cache-Control directives into a map (max-age is numeric).`, idiom: `split(', ') then split('=')` },
  { problemId: 'http-decode-chunked', concept: `Chunked transfer is a hex length, that many bytes, repeat until 0.`, idiom: `read size, read chunk, loop` },
  { problemId: 'http-method-idempotent', concept: `GET, PUT, DELETE, HEAD are idempotent; POST and PATCH are not.`, idiom: `['GET','PUT','DELETE','HEAD'].includes(m)` },
  { problemId: 'http-parse-auth', concept: `An Authorization header is "Scheme credentials".`, idiom: `const [scheme, creds] = h.split(' ')` },
  { problemId: 'http-status-class', concept: `The status class is the first digit (2xx, 4xx...).`, idiom: `Math.floor(status / 100) + 'xx'` },
  { problemId: 'http-conditional-get', concept: `If-None-Match equal to the ETag returns 304 Not Modified.`, idiom: `ifNoneMatch === etag ? 304 : 200` },
  { problemId: 'parse-range-header', concept: `A Range header has the form bytes=start-end.`, idiom: `match the bytes=start-end form`, mistake: `The end may be omitted (to end of file).` },

  // ----- API -----
  { problemId: 'api-offset-paginate', concept: `Offset paging is page*size arithmetic.`, idiom: `items.slice((page - 1) * size, page * size)`, mistake: `Drifts and re-scans under concurrent writes.` },
  { problemId: 'api-validate', concept: `Validate at the boundary and return a per-field error map.`, idiom: `errors[field] = 'required'` },
  { problemId: 'api-etag', concept: `An ETag is a content fingerprint for cheap revalidation.`, idiom: `'W/"' + hash(body) + '"'` },
  { problemId: 'api-pagination', concept: `Cursor paging returns an opaque pointer to where you left off.`, idiom: `take items after the cursor, return a nextCursor`, mistake: `Offset drifts under inserts; cursors do not.` },
  { problemId: 'api-link-header', concept: `RFC 5988 Link header advertises next/prev pages.`, idiom: `<url>; rel="next"` },
  { problemId: 'api-json-response', concept: `A JSON response is status + content-type + a stringified body.`, idiom: `{ status, headers, body: JSON.stringify(data) }` },
  { problemId: 'api-route-match', concept: `Match a method and path to a handler.`, idiom: `routes.find((r) => r.method === m && r.path === p)` },
  { problemId: 'api-create-user-validation', concept: `Validate create-user input, collecting every field error.`, idiom: `check required + type per field` },
  { problemId: 'api-result-to-response', concept: `Map a service result to an HTTP status and body.`, idiom: `result.ok ? 200 : statusForError(result.error)` },
  { problemId: 'api-create-user-handler', concept: `Wire validation, the service call, and the response into one handler.`, idiom: `validate -> create -> 201` },
  { problemId: 'api-filter-builder', concept: `Turn filter params into a predicate or WHERE clause.`, idiom: `build conditions from provided fields only` },

  // ----- Security & auth -----
  { problemId: 'security-constant-time', concept: `Compare secrets in constant time to avoid timing leaks.`, idiom: `XOR-accumulate every byte, check once at the end`, mistake: `=== short-circuits and leaks the matching prefix length.` },
  { problemId: 'security-escape-html', concept: `Escape & < > " ' so untrusted text cannot become markup.`, idiom: `replace & first, then the rest`, mistake: `Escaping & last double-escapes the others.` },
  { problemId: 'security-strong-password', concept: `Score length plus character-class variety.`, idiom: `len >= 8 and mix of upper/lower/digit/symbol` },
  { problemId: 'security-token-bucket', concept: `Tokens refill at a steady rate up to a capacity; each request spends one.`, idiom: `tokens = min(cap, tokens + rate * elapsed)` },
  { problemId: 'security-jwt-payload', concept: `A JWT's middle segment is base64url JSON, readable by anyone.`, idiom: `JSON.parse(atob(parts[1]))`, mistake: `Decoding is not verifying the signature.` },
  { problemId: 'security-rate-limit', concept: `A fixed window counts requests per clock interval.`, idiom: `count per window; over limit -> 429`, mistake: `Allows a double burst at the window boundary.` },
  { problemId: 'security-mask-email', concept: `Mask the local part, keep one char and the domain.`, idiom: `a***@domain.com` },
  { problemId: 'security-safe-join', concept: `Normalize the joined path and confirm it stays under the base.`, idiom: `resolved.startsWith(base)`, mistake: `../ escapes the base directory.` },
  { problemId: 'security-csrf-double-submit', concept: `The cookie token must equal the header/body token.`, idiom: `cookieToken === headerToken` },
  { problemId: 'security-token-parser', concept: `Extract the token after the "Bearer " prefix.`, idiom: `h.startsWith('Bearer ') ? h.slice(7) : null` },
  { problemId: 'auth-has-scope', concept: `Check a required scope is in the granted set.`, idiom: `granted.includes(required)` },

  // ----- Caching & performance -----
  { problemId: 'caching-memoize', concept: `Cache results keyed by the arguments.`, idiom: `if (cache.has(k)) return cache.get(k)` },
  { problemId: 'caching-lru', concept: `LRU evicts the least-recently-used; a Map preserves insertion order.`, idiom: `delete then re-set on access; evict the first key`, mistake: `Not refreshing recency on a read.` },
  { problemId: 'cache-aside', concept: `On a miss, load and store; the loader runs once per key.`, idiom: `key in cache ? hit : load + store` },
  { problemId: 'cache-write-through', concept: `Write to the cache and the store together.`, idiom: `cache[k] = v; store[k] = v` },
  { problemId: 'cache-lfu', concept: `LFU evicts the least-frequently-used entry.`, idiom: `track counts; evict the minimum` },
  { problemId: 'cache-ttl', concept: `Store value plus expiry; treat an expired entry as a miss.`, idiom: `now < entry.expires ? hit : miss` },
  { problemId: 'cache-evict-expired', concept: `Drop entries whose expiry time has passed.`, idiom: `if (now >= e.expires) delete` },
  { problemId: 'perf-chunk', concept: `Slice a list into fixed-size batches.`, idiom: `for (i; i += size) a.slice(i, i + size)` },
  { problemId: 'perf-percentile', concept: `p95 is the value below which 95% of samples fall.`, idiom: `sorted[Math.ceil(0.95 * n) - 1]`, mistake: `Averages hide the slow tail.` },
  { problemId: 'perf-topk', concept: `Count, then sort by frequency for the heavy hitters.`, idiom: `sort by count desc, take k` },
  { problemId: 'perf-ewma', concept: `EWMA weights recent samples more heavily.`, idiom: `ewma = alpha * x + (1 - alpha) * ewma` },

  // ----- Architecture, reliability, messaging -----
  { problemId: 'architecture-backoff', concept: `Exponential backoff spaces retries: base * 2^attempt.`, idiom: `base * 2 ** attempt` },
  { problemId: 'architecture-idempotency', concept: `Dedupe by a stable key, keeping the first result.`, idiom: `seen.has(key) ? stored : process()` },
  { problemId: 'architecture-circuit-breaker', concept: `Open after N failures, half-open to test, close on success.`, idiom: `failures >= threshold -> 'open'` },
  { problemId: 'architecture-idempotent-worker', concept: `A worker skips message ids it already processed.`, idiom: `if (seen.has(id)) return; seen.add(id)` },
  { problemId: 'queue-dlq', concept: `After bounded retries, route the message to a dead-letter queue.`, idiom: `attempts > max -> dlq.push(msg)` },
  { problemId: 'reliability-full-jitter', concept: `Randomize within the capped backoff window.`, idiom: `random(0, min(cap, base * 2 ** n))`, mistake: `Fixed delays cause synchronized retry waves.` },
  { problemId: 'reliability-retry-schedule', concept: `Build the delay sequence for N attempts.`, idiom: `[base, base*2, base*4, ...]` },
  { problemId: 'reliability-retry-until', concept: `Return the index of the first success within max attempts.`, idiom: `find first true within maxAttempts, else -1` },
  { problemId: 'reliability-dedupe-window', concept: `Drop a key seen again within the time window.`, idiom: `now - last >= window ? keep : drop` },
  { problemId: 'reliability-timeout-budget', concept: `Split one deadline across sequential calls.`, idiom: `remaining -= elapsed` },
  { problemId: 'reliability-bulkhead-limit', concept: `Cap concurrent calls per dependency to isolate failures.`, idiom: `inflight < limit ? admit : reject` },
  { problemId: 'reliability-outbox-ready', concept: `Select committed, unsent outbox rows to publish.`, idiom: `rows.filter((r) => !r.sent)` },
  { problemId: 'reliability-idempotency-conflict', concept: `Same key with a different payload is a conflict (409).`, idiom: `stored && stored.body !== body -> conflict` },
  { problemId: 'reliability-retryable-error', concept: `Classify errors as transient (retry) or permanent (do not).`, idiom: `['timeout','503','429'].includes(type)` },
  { problemId: 'reliability-dependency-result', concept: `Wrap a dependency call in an ok/error envelope.`, idiom: `{ ok: true, value } | { ok: false, error }` },
  { problemId: 'backpressure-bounded-queue', concept: `Reject at capacity instead of growing unbounded.`, idiom: `len >= cap ? reject : enqueue` },
  { problemId: 'msg-partition', concept: `Hash the key to a partition so a key's order is preserved.`, idiom: `hash(key) % partitions` },
  { problemId: 'msg-round-robin', concept: `Cycle assignments evenly across workers.`, idiom: `index % workers` },
  { problemId: 'arch-event-sourcing', concept: `Current state is a fold over the event log.`, idiom: `events.reduce(apply, initial)` },
  { problemId: 'arch-saga', concept: `On failure, run compensations for completed steps in reverse.`, idiom: `completed.reverse().forEach(compensate)` },
  { problemId: 'tpc-decision', concept: `Two-phase commit commits only if every participant votes yes.`, idiom: `votes.every((v) => v === 'yes') ? 'commit' : 'abort'` },

  // ----- Distributed, scaling, networking -----
  { problemId: 'dist-consistent-hash', concept: `Walk the hash ring clockwise to the owning node.`, idiom: `ring.find((p) => p >= h) ?? ring[0]` },
  { problemId: 'dist-quorum', concept: `A quorum is a majority: floor(n/2) + 1.`, idiom: `votes > n / 2` },
  { problemId: 'dist-vector-clock', concept: `Compare clocks component-wise for happens-before.`, idiom: `all <= and at least one < => before` },
  { problemId: 'dist-leader-election', concept: `Bully election: the highest reachable id wins.`, idiom: `max(alive ids)` },
  { problemId: 'scale-weighted-pick', concept: `Pick proportionally to weights.`, idiom: `walk cumulative weights` },
  { problemId: 'scale-sliding-window', concept: `Evict timestamps older than the window.`, idiom: `drop t < now - window` },
  { problemId: 'ratelimit-leaky-bucket', concept: `The bucket fills per request and drains at a constant rate.`, idiom: `level = max(0, level - rate * dt) + 1` },
  { problemId: 'lb-expand-weights', concept: `Expand weighted servers into a flat pick pool.`, idiom: `flatMap((s) => Array(s.weight).fill(s.id))` },
  { problemId: 'net-cidr-contains', concept: `A CIDR masks the high bits to test membership.`, idiom: `(ip & mask) === (base & mask)` },
  { problemId: 'net-ip-int', concept: `Pack four octets into a 32-bit int and back.`, idiom: `(a<<24)|(b<<16)|(c<<8)|d, then >>> 0` },
  { problemId: 'net-is-private-ip', concept: `Private ranges are 10/8, 172.16/12, 192.168/16.`, idiom: `check octets against those ranges` },
  { problemId: 'protocol-varint', concept: `A varint stores 7 bits per byte; the high bit means "more".`, idiom: `byte & 0x7f, high bit continues` },

  // ----- Databases -----
  { problemId: 'db-group-by', concept: `Bucket rows by a key in one pass.`, idiom: `(out[key] ||= []).push(row)` },
  { problemId: 'db-hash-join', concept: `Hash one side, probe with the other: linear instead of nested-loop.`, idiom: `index right by key, then probe` },
  { problemId: 'db-keyset-pagination', concept: `Page by "id greater than the last seen", not by offset.`, idiom: `WHERE id > cursor LIMIT n` },
  { problemId: 'db-build-insert', concept: `Build a parameterized INSERT with placeholders.`, idiom: `VALUES ($1, $2)`, mistake: `Never interpolate values into the SQL string.` },
  { problemId: 'db-in-clause', concept: `Build an IN (...) with one placeholder per value.`, idiom: `IN ($1, $2, $3)` },
  { problemId: 'db-optimistic-lock', concept: `Update only if the version still matches what you read.`, idiom: `WHERE id = ? AND version = ?`, mistake: `A mismatch means a concurrent writer won.` },

  // ----- Observability & ops -----
  { problemId: 'obs-log-parse', concept: `Split a fixed-format access log line into fields.`, idiom: `line.split(' ')` },
  { problemId: 'obs-error-rate', concept: `Error rate is errors over total.`, idiom: `errors / total` },
  { problemId: 'obs-histogram', concept: `Cumulative buckets count samples at or below each threshold.`, idiom: `count where value <= le` },
  { problemId: 'obs-apdex', concept: `Apdex = (satisfied + tolerating/2) / total.`, idiom: `(sat + tol / 2) / total` },
  { problemId: 'obs-request-id', concept: `Reuse an inbound request id or generate one.`, idiom: `headers['x-request-id'] ?? generate()` },
  { problemId: 'obs-span-duration', concept: `A span's duration is end minus start.`, idiom: `end - start` },
  { problemId: 'obs-slo-burn-rate', concept: `Burn rate is the actual error rate over the allowed rate.`, idiom: `errorRate / (1 - slo)` },
  { problemId: 'obs-redact-fields', concept: `Redact named fields before logging.`, idiom: `keys.forEach((k) => (out[k] = '***'))` },
  { problemId: 'obs-latency-buckets', concept: `Tally each latency into the first bucket it fits.`, idiom: `find first threshold where ms <= le` },
  { problemId: 'ops-health-rollup', concept: `The worst component status wins: down beats degraded beats ok.`, idiom: `any down -> down; any degraded -> degraded` },

  // ----- Data, parsing, encoding, utilities, strings -----
  { problemId: 'data-luhn', concept: `Luhn doubles every second digit, sums, and checks mod 10.`, idiom: `sum % 10 === 0` },
  { problemId: 'data-rle', concept: `Run-length encoding counts consecutive repeats.`, idiom: `emit count + char per run` },
  { problemId: 'data-csv-to-objects', concept: `The header row becomes keys; map each row to an object.`, idiom: `rows.map((r) => zip(headers, r))` },
  { problemId: 'json-get-path', concept: `Walk a dotted path, stopping safely at undefined.`, idiom: `path.split('.').reduce((o, k) => o?.[k], obj)` },
  { problemId: 'json-deep-equal', concept: `Compare structures recursively, key by key.`, idiom: `same keys, recurse on values` },
  { problemId: 'json-deep-merge', concept: `Merge objects recursively; non-objects replace.`, idiom: `both plain objects -> recurse, else take b` },
  { problemId: 'json-stable-stringify', concept: `Sort keys so equal objects stringify identically.`, idiom: `JSON.stringify(obj, Object.keys(obj).sort())` },
  { problemId: 'json-flatten', concept: `Flatten nested keys into a.b.c paths.`, idiom: `recurse, prefixing each key` },
  { problemId: 'parse-csv-line', concept: `Split on commas, but respect quoted fields.`, idiom: `track an in-quotes flag while scanning` },
  { problemId: 'parse-slugify', concept: `Lowercase, hyphenate non-alphanumeric runs, trim hyphens.`, idiom: `replace non-word runs with -, then trim -` },
  { problemId: 'parse-duration', concept: `Parse "1h30m" into a total of seconds.`, idiom: `match number+unit pairs, sum them` },
  { problemId: 'enc-base64url', concept: `Base64url swaps + and / for - and _ and drops padding.`, idiom: `+ -> -, / -> _, strip =` },
  { problemId: 'enc-hex', concept: `Hex encodes each byte as two hex characters.`, idiom: `byte.toString(16).padStart(2, '0')` },
  { problemId: 'util-semver-compare', concept: `Compare major, then minor, then patch numerically.`, idiom: `compare [maj, min, patch] in order` },
  { problemId: 'util-normalize-path', concept: `Resolve . and .. segments and collapse slashes.`, idiom: `build a stack of path segments` },
  { problemId: 'util-validate-email', concept: `A pragmatic check: one @ with a dot in the domain.`, idiom: `exactly one @, dot after it` },
  { problemId: 'util-diff-arrays', concept: `Set difference: items in A not in B.`, idiom: `a.filter((x) => !setB.has(x))` },
  { problemId: 'str-anagram', concept: `Anagrams share the same sorted letters (or char counts).`, idiom: `sort(a) === sort(b)` },
  { problemId: 'str-lcp', concept: `The longest common prefix shrinks against each string.`, idiom: `trim prefix until every string starts with it` },

  // ----- Realtime, SLA, files/storage, misc -----
  { problemId: 'realtime-sse-format', concept: `A server-sent event is "data: payload" ended by a blank line.`, idiom: `data: <payload>, then a blank line` },
  { problemId: 'sla-error-budget', concept: `The error budget is the allowed failures: (1 - slo) * total.`, idiom: `(1 - slo) * total` },
  { problemId: 'language-data-shapes', concept: `Reshape data between list, map, and grouped forms.`, idiom: `map / filter / reduce into the target shape` },
  { problemId: 'sql-join-practice', concept: `A join links rows from two tables on a shared key.`, idiom: `match left.key === right.key` },
  { problemId: 'storage-object-key', concept: `Join key parts cleanly, trimming stray slashes.`, idiom: `parts.map(trimSlashes).filter(Boolean).join('/')` },
  { problemId: 'storage-validate-upload', concept: `Check size first, then content type, against rules.`, idiom: `too large? bad type? else ok` },
  { problemId: 'storage-presign-valid', concept: `A signed URL is valid while now is within issuedAt + ttl.`, idiom: `now <= issuedAt + ttl` },
  { problemId: 'storage-multipart-assemble', concept: `Order parts by partNumber, then take their etags.`, idiom: `sort by partNumber, map to etag` },
  { problemId: 'storage-content-disposition', concept: `Force a download with a sanitized filename.`, idiom: `attachment; filename="name"` },
  { problemId: 'storage-lifecycle-expire', concept: `Expire objects older than the max age.`, idiom: `filter ageDays > maxAgeDays` },
  { problemId: 'storage-cdn-url', concept: `Join base, bucket, and key without double slashes.`, idiom: `trim trailing slash, then base/bucket/key` },
  { problemId: 'storage-safe-key', concept: `Reject . and .. segments; strip a leading slash.`, idiom: `no '.' or '..' segments allowed` },

  // ----- Node.js mastery -----
  { problemId: 'nodejs-mastery-05-environment-and-process-basics', concept: `Read config from process.env with sane defaults.`, idiom: `process.env.PORT ?? '3000'` },
  { problemId: 'nodejs-mastery-07-express-app-structure', concept: `A router matches method + path to a handler.`, idiom: `routes.find((r) => r.method === m && r.path === p)` },
  { problemId: 'nodejs-mastery-10-error-middleware', concept: `Express error middleware maps an error to a JSON envelope.`, idiom: `(err, req, res, next) => res.status(code).json({ error })` },
  { problemId: 'nodejs-mastery-22-rate-limiting', concept: `Build a limiter key from identity plus action.`, idiom: `"login:" + ip + ":" + email` },
  { problemId: 'nodejs-mastery-12-timers-and-scheduling', concept: `Schedule periodic work at a fixed interval.`, idiom: `setInterval(fn, ms)`, mistake: `Overlapping runs if the work outlasts the interval.` },
  { problemId: 'nodejs-mastery-17-authentication-middleware', concept: `Extract the token after the "Bearer " prefix.`, idiom: `h.startsWith('Bearer ') ? h.slice(7) : null` },
  { problemId: 'nodejs-mastery-21-cors-in-express', concept: `Allow an origin only when it is on the allowlist.`, idiom: `allowlist.includes(origin)`, mistake: `Reflecting any origin with credentials is unsafe.` },
  { problemId: 'nodejs-mastery-34-configuration-validation', concept: `Fail fast at boot if required config keys are missing.`, idiom: `required.filter((k) => !env[k])` },
  { problemId: 'nodejs-mastery-41-api-versioning', concept: `Shape the response per the requested API version.`, idiom: `version === 'v2' ? shapeV2() : shapeV1()` },
  { problemId: 'nodejs-mastery-24-metrics-for-apis', concept: `Label API metrics by method, route, and status class.`, idiom: `{ method, route, status: statusClass }`, mistake: `Labeling by raw path explodes cardinality.` },
  { problemId: 'nodejs-mastery-27-testing-routes', concept: `Enumerate method/path/expected cases as a test matrix.`, idiom: `cases.forEach(([m, p, expected]) => ...)` },
  { problemId: 'nodejs-mastery-31-queues-and-workers', concept: `Retry under the cap, otherwise dead-letter the message.`, idiom: `attempts < max ? retry : deadLetter` },
  { problemId: 'nodejs-mastery-32-graceful-shutdown', concept: `Drain in order: stop accepting, finish in-flight, close pools, exit.`, idiom: `server.close -> drain -> pool.end -> exit` },
  { problemId: 'nodejs-mastery-43-caching-in-node-apis', concept: `Build a stable cache key from the request.`, idiom: `method + path + sorted query` },

  // ----- Python mastery -----
  { problemId: 'python-mastery-25-configuration-loading', concept: `Read settings from the environment with typed defaults.`, idiom: `os.environ.get('PORT', '8000')` },
  { problemId: 'python-mastery-28-testing-with-pytest', concept: `parametrize runs one test across many cases.`, idiom: `@pytest.mark.parametrize('x,expected', cases)` },
  { problemId: 'python-mastery-35-serialization-boundaries', concept: `Serialize only allowlisted fields at the boundary.`, idiom: `{k: obj[k] for k in allowed}`, mistake: `Dumping the whole model leaks internal fields.` },
  { problemId: 'python-mastery-17-http-clients', concept: `Always set a timeout on outbound HTTP calls.`, idiom: `requests.get(url, timeout=5)`, mistake: `No timeout can hang the worker forever.` },
  { problemId: 'python-mastery-23-transactions-in-python', concept: `Wrap multi-step writes in one transaction.`, idiom: `with conn.transaction(): debit; credit` },
  { problemId: 'python-mastery-30-mocking-and-fakes', concept: `A fake records calls so tests can assert behavior.`, idiom: `self.sent.append(message)` },
  { problemId: 'python-mastery-36-timezone-handling', concept: `Store and compare timestamps as timezone-aware UTC.`, idiom: `datetime.now(timezone.utc)`, mistake: `Naive datetimes silently mix zones.` },
  { problemId: 'python-mastery-40-cli-management-commands', concept: `A --dry-run flag previews actions without writing.`, idiom: `'--dry-run' in argv` },
  { problemId: 'python-mastery-08-exceptions-and-error-boundaries', concept: `Map a domain exception to an API error and status.`, idiom: `{'NotFound': 404, 'Invalid': 400}[type]` },
  { problemId: 'python-mastery-11-decorators-for-cross-cutting-behavior', concept: `A decorator wraps a call to time or log it.`, idiom: `start = time(); r = fn(); log(time() - start)` },
  { problemId: 'python-mastery-15-asyncio-fundamentals', concept: `asyncio.gather runs awaitables concurrently.`, idiom: `await asyncio.gather(*tasks)`, mistake: `Awaiting in a loop runs them serially.` },
  { problemId: 'python-mastery-31-celery-rq-background-jobs', concept: `Claim a job by id so it runs exactly once.`, idiom: `if claimed(id): skip else claim(id)` },
  { problemId: 'python-mastery-43-health-checks', concept: `Ready only when every critical dependency is reachable.`, idiom: `all(dep.ok for dep in deps)` },

  // ----- Django mastery -----
  { problemId: 'django-mastery-07-relationships', concept: `Enforce a relationship invariant before saving.`, idiom: `member must belong to the group` },
  { problemId: 'django-mastery-28-drf-permissions', concept: `has_permission gates a request by role or ownership.`, idiom: `request.user.is_staff or obj.owner == user` },
  { problemId: 'django-mastery-29-drf-pagination', concept: `A paginated response wraps results with count/next/previous.`, idiom: `{count, next, previous, results}` },
  { problemId: 'django-mastery-12-transactions-and-atomic', concept: `transaction.on_commit defers side effects until the commit lands.`, idiom: `transaction.on_commit(lambda: enqueue())`, mistake: `Enqueuing before commit can act on rolled-back data.` },
  { problemId: 'django-mastery-20-authorization-patterns', concept: `Scope querysets to the requesting user.`, idiom: `Project.objects.filter(owner=user)` },
  { problemId: 'django-mastery-30-drf-filtering-and-search', concept: `Only allow filtering on allowlisted fields.`, idiom: `apply filters whose field is allowed`, mistake: `Filtering on arbitrary fields leaks data.` },
  { problemId: 'django-mastery-31-drf-error-shapes', concept: `Normalize DRF errors into one consistent shape.`, idiom: `{error: {code, fields}}` },
  { problemId: 'django-mastery-37-celery-with-django', concept: `A task key makes redelivery a no-op.`, idiom: `one key per logical task; skip if seen` },
  { problemId: 'django-mastery-09-filtering-and-managers', concept: `A custom manager encapsulates a common filter.`, idiom: `objects.filter(active=True)` },
  { problemId: 'django-mastery-10-select-related-vs-prefetch-related', concept: `select_related for FK (a JOIN), prefetch_related for M2M/reverse.`, idiom: `select_related('author')`, mistake: `The wrong choice leaves the N+1 in place.` },
  { problemId: 'django-mastery-15-zero-downtime-migrations', concept: `Expand/contract: add nullable, backfill, switch reads, drop old.`, idiom: `add -> backfill -> switch -> drop` },
  { problemId: 'django-mastery-34-testing-django-apis', concept: `Test each role against each endpoint's expected status.`, idiom: `cases of (role, endpoint, status)` },
  { problemId: 'django-mastery-35-performance-query-counts', concept: `Assert an endpoint stays under a query-count budget.`, idiom: `assertNumQueries(n)`, mistake: `An N+1 silently inflates the count.` },
]

// Worked examples (input -> output), merged onto the lessons above and shown by
// Codex under the idiom. Growing batch — fundamentals first.
const examples: Record<string, string> = {
  // Python Fundamentals
  'py-is-even': `4 -> True, 7 -> False`,
  'py-max-of-three': `(3, 9, 5) -> 9`,
  'py-sum-loop': `[1, 2, 3] -> 6`,
  'py-build-range': `3 -> [0, 1, 2]`,
  'py-count-while': `3 -> [3, 2, 1]`,
  'py-evens-up-to': `6 -> [0, 2, 4]`,
  'py-factorial': `5 -> 120, 0 -> 1`,
  'py-fib': `10 -> 55`,
  'py-fizzbuzz': `15 -> "FizzBuzz", 9 -> "Fizz", 7 -> "7"`,
  'py-shout': `"hi" -> "HI"`,
  'py-clean-name': `"  ada lovelace  " -> "Ada Lovelace"`,
  'py-has-substring': `("ell", "hello") -> True`,
  'py-is-url': `"https://x" -> True, "ftp://x" -> False`,
  'py-redact': `("key=abc", "abc") -> "key=***"`,
  'py-csv-join': `["a", "b", "c"] -> "a,b,c"`,
  'py-count-char': `("banana", "a") -> 3`,
  'py-reverse-string': `"abc" -> "cba"`,
  'py-reverse-words': `"a b c" -> "c b a"`,
  'py-first-n': `([1, 2, 3, 4], 2) -> [1, 2]`,
  'py-position': `([10, 20], 20) -> 1, missing -> -1`,
  'py-sort-desc': `[3, 1, 2] -> [3, 2, 1]`,
  'py-sort-by-len': `["bbb", "a", "cc"] -> ["a", "cc", "bbb"]`,
  'py-min-max': `[3, 1, 2] -> [1, 3]`,
  'py-with-index': `["a", "b"] -> [(0, "a"), (1, "b")]`,
  'py-pair-up': `([1, 2], ["a", "b"]) -> [(1, "a"), (2, "b")]`,
  'py-word-count': `"a a b" -> {"a": 2, "b": 1}`,
  'py-safe-get': `({"a": 1}, "b", 0) -> 0`,
  'py-keys-sorted': `{"b": 1, "a": 2} -> ["a", "b"]`,
  'py-merge-dicts': `({"a": 1}, {"b": 2}) -> {"a": 1, "b": 2}`,
  'py-invert-dict': `{"a": 1} -> {1: "a"}`,
  'py-squares-even': `[1, 2, 3, 4] -> [4, 16]`,
  'py-common-elements': `([1, 2, 3], [2, 3, 4]) -> [2, 3]`,
  'py-all-positive': `[1, 2, 3] -> True, [1, -1] -> False`,
  'py-safe-divide': `(10, 2) -> 5.0, (1, 0) -> None`,
  'py-memoize': `second call with the same args skips the work`,
  'py-group-by': `([1, 2, 3, 4], is_even) -> {"odd": [1, 3], "even": [2, 4]}`,
  'py-match-route': `("/users/:id", "/users/42") -> {"id": "42"}`,
  'py-string-format': `("Ada", 3) -> "Ada has 3 items"`,
  'py-zip-dict': `(["a", "b"], [1, 2]) -> {"a": 1, "b": 2}`,
  'py-flatten': `[[1, 2], [3]] -> [1, 2, 3]`,
  'py-filter-lambda': `[-1, 2, -3, 4] -> [2, 4]`,
  'py-dedupe-order': `[1, 2, 1, 3] -> [1, 2, 3]`,
  'py-sort-dicts': `([{"n": 3}, {"n": 1}], "n") -> [{"n": 1}, {"n": 3}]`,
  'py-max-by-key': `(["a", "ccc", "bb"], len) -> "ccc"`,
  'py-class-counter': `c.increment() -> 1, c.increment() -> 2`,
  'py-json-roundtrip': `{"a": [1, 2]} -> {"a": [1, 2]}`,
  'py-defaultdict-group': `([1, 2, 3, 4], is_even) -> {"o": [1, 3], "e": [2, 4]}`,
  'py-is-palindrome': `"racecar" -> True, "hello" -> False`,
  'py-chunk': `([1, 2, 3, 4, 5], 2) -> [[1, 2], [3, 4], [5]]`,
  'py-running-total': `[1, 2, 3, 4] -> [1, 3, 6, 10]`,
  'py-rotate': `([1, 2, 3, 4, 5], 2) -> [4, 5, 1, 2, 3]`,
  'py-merge-sum': `({"x": 1, "y": 2}, {"y": 3}) -> {"x": 1, "y": 5}`,
  'py-count-words': `"a b a c b a" -> {"a": 3, "b": 2, "c": 1}`,
  'py-two-sum': `([2, 7, 11], 9) -> [0, 1]`,
  'py-flatten-deep': `[1, [2, [3]]] -> [1, 2, 3]`,
  'py-fib-memo': `10 -> 55`,
  'py-anagram-groups': `["eat", "tea", "bat"] -> [["bat"], ["eat", "tea"]]`,

  // JavaScript Fundamentals
  'jsf-sum-for': `[1, 2, 3] -> 6`,
  'jsf-countdown-while': `3 -> [3, 2, 1]`,
  'jsf-map-double': `[1, 2, 3] -> [2, 4, 6]`,
  'jsf-filter-evens': `[1, 2, 3, 4] -> [2, 4]`,
  'jsf-reduce-product': `[2, 3, 4] -> 24`,
  'jsf-foreach-total': `[1, 2, 3] -> 6`,
  'jsf-shout': `"hi" -> "HI"`,
  'jsf-join-csv': `["a", "b"] -> "a,b"`,
  'jsf-contains': `([1, 2], 2) -> true`,
  'jsf-position-of': `([10, 20], 20) -> 1`,
  'jsf-first-n': `([1, 2, 3], 2) -> [1, 2]`,
  'jsf-key-count': `{ a: 1, b: 2 } -> 2`,
  'jsf-entries': `{ a: 1 } -> [["a", 1]]`,
  'jsf-reverse-str': `"abc" -> "cba"`,
  'jsf-fizzbuzz': `15 -> "FizzBuzz", 9 -> "Fizz"`,

  // Node Fundamentals
  'node-fundamentals-01-sum-with-for-loop': `[1, 2, 3] -> 6`,
  'node-fundamentals-02-count-even-numbers': `[1, 2, 3, 4] -> 2`,
  'node-fundamentals-03-while-countdown': `3 -> [3, 2, 1]`,
  'node-fundamentals-04-map-user-names': `[{ name: "Ada" }] -> ["Ada"]`,
  'node-fundamentals-05-filter-active-users': `[{ active: true }, { active: false }] -> [the active one]`,
  'node-fundamentals-06-find-by-id': `([{ id: 1 }], 1) -> { id: 1 }, missing -> undefined`,
  'node-fundamentals-07-count-by-status': `[{ status: "a" }, { status: "a" }] -> { a: 2 }`,
  'node-fundamentals-08-safe-json-parse': `'{"a":1}' -> { a: 1 }, "oops" -> null`,
  'node-fundamentals-09-require-fields': `({ name: "x" }, ["name", "email"]) -> ["email"]`,
  'node-fundamentals-10-normalize-email': `"  A@B.COM " -> "a@b.com"`,
  'node-fundamentals-11-slug-from-title': `"Hello World!" -> "hello-world"`,
  'node-fundamentals-12-parse-integer-param': `("42", 1) -> 42, ("", 1) -> 1`,
  'node-fundamentals-13-build-query-string': `{ a: 1, b: 2 } -> "a=1&b=2"`,
  'node-fundamentals-14-read-header-case-insensitive': `({ "content-type": "x" }, "Content-Type") -> "x"`,
  'node-fundamentals-15-basic-auth-parser': `"Basic dXNlcjpwYXNz" -> ["user", "pass"]`,
  'node-fundamentals-16-error-envelope': `("BAD", "msg") -> { error: { code: "BAD", message: "msg" } }`,
  'node-fundamentals-17-compose-middleware': `runs each middleware in order on the context`,
  'node-fundamentals-18-promise-all-settled-summary': `[fulfilled, rejected] -> { fulfilled: 1, rejected: 1 }`,
  'node-fundamentals-19-timeout-race-shape': `-> { ok: false, reason: "timeout" }`,
  'node-fundamentals-20-retryable-status': `503 -> true, 400 -> false`,
  'node-fundamentals-21-buffer-byte-length': `"é" -> 2`,
  'node-fundamentals-22-chunk-array-for-batches': `([1, 2, 3, 4, 5], 2) -> [[1, 2], [3, 4], [5]]`,
  'node-fundamentals-23-idempotency-key': `a repeated key returns the stored result`,
  'node-fundamentals-24-redact-secret-fields': `{ password: "x" } -> { password: "***" }`,
  'node-fundamentals-25-request-log-line': `("GET", "/x", 200, 5) -> "GET /x 200 5ms"`,

  // API drills
  'apidrill-route-match': `([{ method: "GET", path: "/users", handler: "list" }], "GET", "/users") -> "list"`,
  'apidrill-parse-params': `({ page: "2" }) -> { page: 2, limit: 20, sort: "id" }`,
  'apidrill-status-for-error': `"not_found" -> 404, "weird" -> 500`,
  'apidrill-paginate': `([1,2,3,4,5], 1, 2) -> { data: [1,2], page: 1, perPage: 2, total: 5, totalPages: 3 }`,
  'apidrill-validate-body': `({ name: { required: true } }, {}) -> { valid: false, errors: { name: "required" } }`,
  'apidrill-serialize': `{ id: 1, password: "x" } -> { id: 1 }`,
  'apidrill-authorize': `(null, "admin") -> 401, ({ role: "user" }, "admin") -> 403`,
  'apidrill-method-guard': `(["GET"], "DELETE") -> 405`,
  'apidrill-json-response': `(200, { ok: true }) -> { status: 200, body: '{"ok":true}' }`,
  'apidrill-error-envelope': `("BAD", "msg") -> { error: { code: "BAD", message: "msg" } }`,
  'apidrill-crud-handler': `GET (no id) -> { status: 200, body: list }, POST -> { status: 201, ... }`,
  'apidrill-rate-headers': `(100, 99, 60) -> { "X-RateLimit-Limit": "100", "X-RateLimit-Remaining": "99" }`,
  'apidrill-path-params': `("/users/:id", "/users/42") -> { id: "42" }`,
  'apidrill-rest-router': `GET /users/9 -> { handler: "getUser", params: { id: "9" } }`,
  'apidrill-pagination-links': `("/items", 2, 3) -> { self, first, last, next, prev }`,
  'apidrill-merge-patch': `({ a: 1, b: 2 }, { b: null, c: 3 }) -> { a: 1, c: 3 }`,
  'apidrill-parse-sort': `"-created,name" -> [{ field: "created", dir: "desc" }, { field: "name", dir: "asc" }]`,
  'apidrill-list-envelope': `([1,2], 1, 2, 5) -> { data: [1,2], meta: { total: 5, totalPages: 3 } }`,
  'apidrill-require-fields': `({ name: "a" }, ["name", "email"]) -> ["email"]`,
  'apidrill-content-type': `"json" -> "application/json", "xyz" -> "application/octet-stream"`,

  // SQL drills
  'sqldrill-select-where': `([{ a: 1 }, { a: 2 }], a > 1) -> [{ a: 2 }]`,
  'sqldrill-project': `([{ a: 1, b: 2 }], ["a"]) -> [{ a: 1 }]`,
  'sqldrill-order-by': `([{ n: 3 }, { n: 1 }], "n", "asc") -> [{ n: 1 }, { n: 3 }]`,
  'sqldrill-limit-offset': `([1,2,3,4], 2, 1) -> [2, 3]`,
  'sqldrill-distinct': `([{ id: 1 }, { id: 1 }, { id: 2 }], "id") -> [{ id: 1 }, { id: 2 }]`,
  'sqldrill-count-by': `([{ t: "a" }, { t: "a" }, { t: "b" }], "t") -> { a: 2, b: 1 }`,
  'sqldrill-sum': `([{ n: 1 }, { n: 2 }], "n") -> 3`,
  'sqldrill-avg': `([{ n: 2 }, { n: 4 }], "n") -> 3, [] -> 0`,
  'sqldrill-inner-join': `join rows where left.uid === right.id, merging both`,
  'sqldrill-update-where': `set { done: true } on rows where id === 1`,

  // TypeScript drills
  'ts-typed-sum': `[1, 2, 3] -> 6`,
  'ts-greet': `"Ada" -> a greeting string`,
  'ts-optional-param': `f() and f(5) are both valid`,
  'ts-interface': `{ id: 1, name: "x" } satisfies User`,
  'ts-discriminated-union': `{ kind: "square", s: 3 } -> 9`,
  'ts-generic-identity': `identity(5) -> 5 (type stays number)`,
  'ts-generic-first': `[1, 2] -> 1, [] -> undefined`,
  'ts-keyof-pluck': `({ id: 1, name: "x" }, "name") -> "x"`,
  'ts-record-countby': `["a", "a", "b"] -> { a: 2, b: 1 }`,
  'ts-partial-defaults': `Partial<Config> lets you pass { timeout: 5 } only`,
  'ts-map-values': `({ a: 1 }, (x) => x * 2) -> { a: 2 }`,
  'ts-as-const-union': `["a", "b"] as const -> type "a" | "b"`,
  'ts-type-guard': `isString("x") -> true, isString(1) -> false`,
  'ts-omit': `Omit<User, "password"> -> { id, name }`,
  'ts-pick': `Pick<User, "id" | "name"> -> { id, name }`,
  'ts-required': `Required<Config> -> every field mandatory`,
  'ts-readonly': `Readonly<User> -> fields cannot be reassigned`,
  'ts-tuple': `[3, 1, 2] -> [1, 3]`,
  'ts-generic-constraint': `byId([{ id: 1 }]) ok; byId([{}]) is a type error`,
  'ts-mapped-type': `Flags<User> -> { id: boolean, name: boolean }`,
  'ts-enum': `Status.Active -> 0`,
  'ts-union-return': `found -> User, missing -> null`,
  'ts-stack-class': `push(1); push(2); pop() -> 2`,
  'ts-result-map': `mapResult({ ok: true, value: 2 }, x => x * 10) -> { ok: true, value: 20 }`,
  'ts-compact': `[1, null, 2, undefined] -> [1, 2]`,
  'ts-from-entries': `[["a", 1], ["b", 2]] -> { a: 1, b: 2 }`,
  'ts-exhaustive': `every union case handled; a new case becomes a compile error`,
  'ts-group-by': `([1,2,3,4], even) -> { odd: [1,3], even: [2,4] }`,
  'ts-pick-keys': `({ a: 1, b: 2 }, ["a"]) -> { a: 1 }`,
  'ts-merge': `({ a: 1 }, { b: 2 }) -> { a: 1, b: 2 }`,

  // Algorithms & data structures
  'algo-binary-search': `([1,3,5,7], 5) -> 2, missing -> -1`,
  'algo-merge-intervals': `[[1,3],[2,4]] -> [[1,4]]`,
  'algo-merge-sorted': `([1,3], [2,4]) -> [1,2,3,4]`,
  'algo-two-sum': `([2,7,11], 9) -> [0, 1]`,
  'algo-valid-parens': `"(())" -> true, "(]" -> false`,
  'algo-kth-largest': `([3,1,5,2], 2) -> 3`,
  'algo-gcd': `(12, 8) -> 4`,
  'ds-trie-autocomplete': `prefix "ca" -> ["car", "cat"]`,
  'ds-moving-average': `window 3 over a stream -> the running average`,

  // Internet & HTTP
  'internet-request-line': `"GET /users?page=2 HTTP/1.1" -> { method: "GET", target: "/users?page=2", version: "HTTP/1.1" }`,
  'internet-parse-cookies': `"a=1; b=2" -> { a: "1", b: "2" }`,
  'internet-build-response': `(200, "hi") -> a status line, headers, a blank line, then "hi"`,
  'internet-content-negotiation': `("application/json, text/html;q=0.9", servable) -> "application/json"`,
  'internet-query-parser': `"a=1&b=2" -> { a: "1", b: "2" }`,
  'http-build-query': `{ a: 1, b: 2 } -> "a=1&b=2"`,
  'http-parse-cache-control': `"max-age=60, public" -> { "max-age": 60, public: true }`,
  'http-decode-chunked': `a "2" length line + "hi" + a "0" terminator -> "hi"`,
  'http-method-idempotent': `"GET" -> true, "POST" -> false`,
  'http-parse-auth': `"Bearer abc" -> { scheme: "Bearer", credentials: "abc" }`,
  'http-status-class': `200 -> "2xx", 404 -> "4xx"`,
  'http-conditional-get': `(etag "v1", If-None-Match "v1") -> 304`,
  'parse-range-header': `"bytes=0-499" -> { start: 0, end: 499 }`,

  // API (handlers and helpers)
  'api-offset-paginate': `([1,2,3,4,5], 2, 2) -> [3, 4]`,
  'api-validate': `({}, { name: required }) -> { name: "required" }`,
  'api-etag': `"hello" -> 'W/"<hash>"'`,
  'api-pagination': `(items, cursor) -> { data, nextCursor }`,
  'api-link-header': `("/items?page=3", "next") -> '</items?page=3>; rel="next"'`,
  'api-json-response': `(200, { ok: true }) -> { status: 200, body: '{"ok":true}' }`,
  'api-route-match': `([{ method: "GET", path: "/x" }], "GET", "/x") -> the handler`,
  'api-create-user-validation': `{ email: "" } -> { email: "required" }`,
  'api-result-to-response': `{ ok: true, value: u } -> { status: 200, body: u }`,
  'api-create-user-handler': `a valid body -> { status: 201, body: user }`,
  'api-filter-builder': `{ status: "active" } -> a predicate matching status === "active"`,

  // Security & auth
  'security-constant-time': `("abc", "abc") -> true, ("abc", "abd") -> false (same time taken)`,
  'security-escape-html': `"<b>" -> "&lt;b&gt;"`,
  'security-strong-password': `"abc" -> weak, "Abc12345!" -> strong`,
  'security-token-bucket': `capacity 10, refills over time; each request spends 1`,
  'security-jwt-payload': `"h.eyJ1aWQiOjF9.s" -> { uid: 1 }`,
  'security-rate-limit': `limit 5/min; the 6th request in the window -> 429`,
  'security-mask-email': `"ada@x.com" -> "a***@x.com"`,
  'security-safe-join': `("/base", "../etc") -> rejected, ("/base", "a/b") -> "/base/a/b"`,
  'security-csrf-double-submit': `(cookie "t1", header "t1") -> ok, mismatch -> reject`,
  'security-token-parser': `"Bearer abc" -> "abc", "Basic x" -> null`,
  'auth-has-scope': `(["read", "write"], "write") -> true`,

  // Caching & performance
  'caching-memoize': `slow(2) computes once; slow(2) again -> the cached result`,
  'caching-lru': `capacity 2: adding a third key evicts the least-recently-used`,
  'cache-aside': `miss -> load + store, hit -> the stored value`,
  'cache-write-through': `set(k, v) -> both cache and store hold v`,
  'cache-lfu': `capacity 2: the least-frequently-used key is evicted`,
  'cache-ttl': `set with ttl 60; read at 70s -> a miss`,
  'cache-evict-expired': `entries past their expiry are dropped`,
  'perf-chunk': `([1,2,3,4,5], 2) -> [[1,2], [3,4], [5]]`,
  'perf-percentile': `(latencies, 95) -> the p95 value`,
  'perf-topk': `(["a","a","b"], 1) -> ["a"]`,
  'perf-ewma': `alpha 0.5 over [10, 20] -> 15`,

  // Architecture, reliability, messaging
  'architecture-backoff': `(base 100, attempt 3) -> 800`,
  'architecture-idempotency': `the same key twice -> processed once`,
  'architecture-circuit-breaker': `5 failures -> "open", a success -> "closed"`,
  'architecture-idempotent-worker': `a replayed message id -> skipped`,
  'queue-dlq': `after 3 failed retries -> moved to the DLQ`,
  'reliability-full-jitter': `(cap 1000, attempt 3) -> random(0, 1000)`,
  'reliability-retry-schedule': `(base 100, 3 attempts) -> [100, 200, 400]`,
  'reliability-retry-until': `([false, false, true], 5) -> 2`,
  'reliability-dedupe-window': `the same key within 1000ms -> dropped`,
  'reliability-timeout-budget': `budget 1000, used 300 -> 700 remaining`,
  'reliability-bulkhead-limit': `limit 2: the 3rd concurrent call -> rejected`,
  'reliability-outbox-ready': `rows where sent === false`,
  'reliability-idempotency-conflict': `same key, different body -> conflict (409)`,
  'reliability-retryable-error': `"timeout" -> true, "validation" -> false`,
  'reliability-dependency-result': `ok -> { ok: true, value }, fail -> { ok: false, error }`,
  'backpressure-bounded-queue': `capacity 3, already full -> reject`,
  'msg-partition': `("user-42", 4 partitions) -> a stable partition index`,
  'msg-round-robin': `3 workers: tasks go 0, 1, 2, 0, 1, 2`,
  'arch-event-sourcing': `[Deposited 100, Withdrew 30] -> balance 70`,
  'arch-saga': `step 3 fails -> compensate step 2, then step 1`,
  'tpc-decision': `["yes", "yes"] -> "commit", ["yes", "no"] -> "abort"`,

  // Distributed, scaling, networking
  'dist-consistent-hash': `adding a node moves only keys between two ring points`,
  'dist-quorum': `n 3 -> quorum is 2`,
  'dist-vector-clock': `{ a: 1 } vs { a: 2 } -> the first happens-before the second`,
  'dist-leader-election': `alive ids [1, 3, 2] -> leader 3`,
  'scale-weighted-pick': `weights { a: 1, b: 3 } -> b chosen ~3x as often`,
  'scale-sliding-window': `requests older than the window are evicted`,
  'ratelimit-leaky-bucket': `steady drain; a burst over capacity -> rejected`,
  'lb-expand-weights': `[{ id: "a", weight: 2 }] -> ["a", "a"]`,
  'net-cidr-contains': `("10.0.0.0/8", "10.1.2.3") -> true`,
  'net-ip-int': `"1.2.3.4" -> 16909060 -> "1.2.3.4"`,
  'net-is-private-ip': `"10.0.0.1" -> true, "8.8.8.8" -> false`,
  'protocol-varint': `300 -> two bytes -> 300`,

  // Databases
  'db-group-by': `([{ t: "a" }, { t: "b" }, { t: "a" }], "t") -> { a: [...], b: [...] }`,
  'db-hash-join': `join users and orders on id in linear time`,
  'db-keyset-pagination': `last id 50 -> WHERE id > 50 LIMIT 20`,
  'db-build-insert': `("users", { name: "x" }) -> "INSERT INTO users (name) VALUES ($1)"`,
  'db-in-clause': `[1, 2, 3] -> "IN ($1, $2, $3)"`,
  'db-optimistic-lock': `version 3 matches -> update, mismatch -> rejected`,

  // Observability & ops
  'obs-log-parse': `"GET /x 200 5" -> { method, path, status, ms }`,
  'obs-error-rate': `(5 errors, 100 total) -> 0.05`,
  'obs-histogram': `samples + bucket thresholds -> cumulative counts`,
  'obs-apdex': `(80 satisfied, 10 tolerating, 100 total) -> 0.85`,
  'obs-request-id': `an inbound id is reused, otherwise a new one is generated`,
  'obs-span-duration': `(start 100, end 130) -> 30`,
  'obs-slo-burn-rate': `(error rate 0.02, slo 0.99) -> 2`,
  'obs-redact-fields': `({ password: "x" }, ["password"]) -> { password: "***" }`,
  'obs-latency-buckets': `120ms -> the "<=250ms" bucket`,
  'ops-health-rollup': `["ok", "degraded"] -> "degraded", any "down" -> "down"`,

  // Data, parsing, encoding, utilities, strings
  'data-luhn': `"4539578763621486" -> valid`,
  'data-rle': `"aaabb" -> "a3b2"`,
  'data-csv-to-objects': `header "a,b" + row "1,2" -> [{ a: "1", b: "2" }]`,
  'json-get-path': `({ a: { b: 2 } }, "a.b") -> 2, missing -> undefined`,
  'json-deep-equal': `({ a: [1] }, { a: [1] }) -> true`,
  'json-deep-merge': `({ a: { x: 1 } }, { a: { y: 2 } }) -> { a: { x: 1, y: 2 } }`,
  'json-stable-stringify': `{ b: 1, a: 2 } -> '{"a":2,"b":1}'`,
  'json-flatten': `{ a: { b: 1 } } -> { "a.b": 1 }`,
  'parse-csv-line': `'a,"b,c",d' -> ["a", "b,c", "d"]`,
  'parse-slugify': `"Hello, World!" -> "hello-world"`,
  'parse-duration': `"1h30m" -> 5400`,
  'enc-base64url': `base64 "a+b/c=" -> url-safe "a-b_c"`,
  'enc-hex': `[255, 16] -> "ff10" -> [255, 16]`,
  'util-semver-compare': `("1.2.0", "1.10.0") -> -1`,
  'util-normalize-path': `"/a/b/../c" -> "/a/c"`,
  'util-validate-email': `"a@b.com" -> true, "a@b" -> false`,
  'util-diff-arrays': `([1, 2, 3], [2, 3]) -> [1] (in A, not in B)`,
  'str-anagram': `("listen", "silent") -> true`,
  'str-lcp': `["flow", "flower", "flight"] -> "fl"`,

  // Realtime, SLA, misc, files/storage
  'realtime-sse-format': `(data "hi") -> a "data: hi" line followed by a blank line`,
  'sla-error-budget': `(slo 0.99, 1000 total) -> 10 allowed failures`,
  'language-data-shapes': `[{ id: 1, tag: "a" }] -> { a: [1] } (grouped)`,
  'sql-join-practice': `users + orders on user_id -> rows carrying both`,
  'storage-object-key': `["users", "42", "a.png"] -> "users/42/a.png"`,
  'storage-validate-upload': `(2MB, "image/png"), max 1MB -> "too_large"`,
  'storage-presign-valid': `(issued 1000, ttl 60, now 1100) -> false`,
  'storage-multipart-assemble': `[{ n: 2 }, { n: 1 }] -> etags ordered [1, 2]`,
  'storage-content-disposition': `"report.pdf" -> 'attachment; filename="report.pdf"'`,
  'storage-lifecycle-expire': `objects older than 7 days -> expired`,
  'storage-cdn-url': `("https://cdn/", "assets", "a.png") -> "https://cdn/assets/a.png"`,
  'storage-safe-key': `"a/../b" -> rejected, "a/b" -> "a/b"`,

  // Node.js mastery
  'nodejs-mastery-05-environment-and-process-basics': `PORT unset -> "3000"`,
  'nodejs-mastery-07-express-app-structure': `("GET", "/x") -> the matching handler`,
  'nodejs-mastery-10-error-middleware': `an error -> { status, body: { error } }`,
  'nodejs-mastery-22-rate-limiting': `(ip "1.2.3.4", "ada@x") -> "login:1.2.3.4:ada@x"`,
  'nodejs-mastery-12-timers-and-scheduling': `interval 1000 -> fires every 1000ms`,
  'nodejs-mastery-17-authentication-middleware': `"Bearer abc" -> "abc"`,
  'nodejs-mastery-21-cors-in-express': `an origin on the allowlist -> allowed`,
  'nodejs-mastery-34-configuration-validation': `missing PORT -> ["PORT"]`,
  'nodejs-mastery-41-api-versioning': `"v2" -> the v2 response shape`,
  'nodejs-mastery-24-metrics-for-apis': `{ method: "GET", route: "/x", status: "2xx" }`,
  'nodejs-mastery-27-testing-routes': `cases of (method, path, expectedStatus)`,
  'nodejs-mastery-31-queues-and-workers': `attempts 4, max 3 -> dead-letter`,
  'nodejs-mastery-32-graceful-shutdown': `SIGTERM -> close, drain, end pool, exit`,
  'nodejs-mastery-43-caching-in-node-apis': `("GET", "/x", { a: 1 }) -> a stable cache key`,

  // Python mastery
  'python-mastery-25-configuration-loading': `PORT unset -> "8000"`,
  'python-mastery-28-testing-with-pytest': `cases -> one test runs per case`,
  'python-mastery-35-serialization-boundaries': `a model -> only allowlisted fields`,
  'python-mastery-17-http-clients': `requests.get(url, timeout=5)`,
  'python-mastery-23-transactions-in-python': `debit + credit inside one transaction`,
  'python-mastery-30-mocking-and-fakes': `fake.send(msg) -> recorded in fake.sent`,
  'python-mastery-36-timezone-handling': `a naive datetime -> rejected, UTC-aware -> ok`,
  'python-mastery-40-cli-management-commands': `argv has --dry-run -> True`,
  'python-mastery-08-exceptions-and-error-boundaries': `NotFound -> 404`,
  'python-mastery-11-decorators-for-cross-cutting-behavior': `@timed wraps a call and logs its duration`,
  'python-mastery-15-asyncio-fundamentals': `gather(t1, t2) -> [r1, r2] concurrently`,
  'python-mastery-31-celery-rq-background-jobs': `claim(id) once; a second claim -> skipped`,
  'python-mastery-43-health-checks': `all deps ok -> ready, one down -> not ready`,

  // Django mastery
  'django-mastery-07-relationships': `a member not in the group -> rejected`,
  'django-mastery-28-drf-permissions': `staff or owner -> allowed`,
  'django-mastery-29-drf-pagination': `{ count, next, previous, results }`,
  'django-mastery-12-transactions-and-atomic': `on_commit(enqueue) -> runs only after commit`,
  'django-mastery-20-authorization-patterns': `Project.objects.filter(owner=user)`,
  'django-mastery-30-drf-filtering-and-search': `filter on an allowlisted field only`,
  'django-mastery-31-drf-error-shapes': `a DRF error -> { error: { code, fields } }`,
  'django-mastery-37-celery-with-django': `the same task key -> runs once`,
  'django-mastery-09-filtering-and-managers': `objects.active() -> active rows only`,
  'django-mastery-10-select-related-vs-prefetch-related': `FK -> select_related, M2M -> prefetch_related`,
  'django-mastery-15-zero-downtime-migrations': `add nullable -> backfill -> switch -> drop`,
  'django-mastery-34-testing-django-apis': `(role, endpoint) -> the expected status`,
  'django-mastery-35-performance-query-counts': `assertNumQueries(3) guards against an N+1`,
}

export const problemLessons: ProblemLesson[] = lessonBase.map((l) =>
  examples[l.problemId] ? { ...l, example: examples[l.problemId] } : l,
)
